### PR TITLE
hotfix: fix regression of attention api change in intel platform

### PR DESCRIPTION
**Pull request by sywangyi**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sywangyi** [comment]
@Narsil @danieldk please help review. regression brought by https://github.com/huggingface/text-generation-inference/commit/b70ae0969f11bae03a3c6194fc8c592a1d8a65b3

**Comment by sywangyi** [comment]
@Narsil @danieldk could you review it ASAP, thanks. Without the fix, the intel xpu/cpu image function is broken.

**Comment by sywangyi** [comment]
the failures are not caused by this PR. 
show  https://huggingface.co/huggingface/llama-7b/resolve/main/tokenizer_config.json is not accessible

**Review by Narsil — DISMISSED** [review]

**Comment by sywangyi** [comment]
fix the conflict and fix the failure caused by https://github.com/huggingface/text-generation-inference/pull/2449

**Comment by sywangyi** [comment]
Is it possible that we add ipex cpu CI to avoid such incompatible issue in the future?

**Comment by sywangyi** [comment]
@Narsil  could you help revisit the PR? seems the CI build failure is "Error: Username and password required", not caused by the PR;

**Comment by ErikKaum** [comment]
Hi @sywangyi 

Yes, I can do the same here as for #2444 so that we know that tests pass 👍

**Comment by sywangyi** [comment]
> Hi @sywangyi
> 
> Yes, I can do the same here as for #2444 so that we know that tests pass 👍

any result about the test?

**Review by ErikKaum — APPROVED** [review]

**Pull request merged**
