### PR TITLE
fix: launcher doc typos

### PR DESCRIPTION
**Pull request by thelinuxkid**
# What does this PR do?

fixes launcher doc typos

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@OlivierDehaene OR @Narsil

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Narsil** [comment]
Thanks ! I moved the code in https://github.com/huggingface/text-generation-inference/pull/1473 since I couldn't push here.

**Comment by thelinuxkid** [comment]
Thanks @Narsil ! Was hoping to get that contributor cred. Next time!

**Comment by Narsil** [comment]
You will ! your commit is still in it !

**Comment by Narsil** [comment]
I reopened the PR, if you want to cherry-pick my fix, and we use this PR instead it's fine by me (didn't have time to merge anyway)

https://github.com/huggingface/text-generation-inference/pull/1473/commits

**Comment by thelinuxkid** [comment]
Thanks @Narsil. Done! I've rebased with main and put your commit on top.

**Pull request merged**
