### PR TITLE
OpenAI function calling compatible support

### PR DESCRIPTION
**Pull request by phangiabao98**
# What does this PR do?

Fixes # (issue)
https://github.com/huggingface/text-generation-inference/issues/1887

## Before submitting
- [no ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [yes] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ yes] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [yes ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ yes] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@Narsil

 -->

### CODE REVIEW

**Comment by drbh** [comment]
thanks for the contribution! 

just opened another PR just to run CI https://github.com/huggingface/text-generation-inference/pull/1894

**Comment by drbh** [comment]
@phangiabao98 would you be able to run `cargo fmt` or `pre-commit run --all-files` and push another commit. 

Once thats fixed I'll approve and merged. Thanks!

**Comment by phangiabao98** [comment]
@drbh have just run cargo fmt and push another commit as your instruction.
https://github.com/huggingface/text-generation-inference/commit/2295f3268956c0896d559689e3c12bda8d01dcde

Please help to review and merge. Thanks !

**Comment by phangiabao98** [comment]
@Narsil I tested with python function call implementation as mention in https://github.com/huggingface/text-generation-inference/issues/1887. Endpoint /chat/completion works fine.

Believe that the commits only impact on response of /chat/completion endpoint so other endpoint would not be impact.

Would you prefer adding this change into changelog ?

**Comment by Narsil** [comment]
Thanks !

**Pull request merged**
