### PR TITLE
Fix local load for Medusa

### LINKED ISSUE #1415: How to use local Medusa head?
It is said that Medusa can significantly accelerate inference speed. During my attempts to utilize it, I have observed that it does not support the use of local Medusa config and head. The code fragment I discovered that pertains to this functionality is as follows, which I have modified. However, I do not comprehend the meaning of 'medusa_sf'. The training process of Medusa does not generate new safetensors. What is this? 
```python
medusa_config = f"{model_id}/config_medusa.json"
# medusa_config = hf_hub_download(
#     use_medusa, revision=revision, filename="config.json"
# )
with open(medusa_config, "r") as f:
    config = json.load(f)
medusa_head = f"{model_id}/medusa_lm_head.pt"
# medusa_head = hf_hub_download(
#     use_medusa, revision=revision, filename="medusa_lm_head.pt"
# )
medusa_sf = medusa_head[: -len(".pt")] + ".safetensors"
weights = Weights(
    [medusa_sf], device, dtype, process_group=self.process_group
)
lm_head = model.lm_head
model.lm_head = MedusaModel(config, weights, lm_head)
```

How should I employ TGI to access the local Medusa? A huge thank for your work!

### LINKED ISSUE #1418: Medusa can't load from local
### System Info

TGI 1.3.4

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Medusa can't load from local
I believe the following two locations need to be fixed.
I test my code for LLaMA with Medusa. Hope it can provide some reference.
https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/cli.py#L201

```
    else:
        # Try to load as a local PEFT model
        try:
            utils.download_and_unload_peft(
                model_id, revision, trust_remote_code=trust_remote_code
            )
            utils.weight_files(model_id, revision, extension)
            return
        except Exception:
            pass

        try:
            import json

            medusa_head = os.path.join(model_id, "medusa_lm_head.pt")
            if auto_convert:
                medusa_sf = Path(medusa_head[: -len(".pt")] + ".safetensors")
                if not medusa_sf.exists():
                    utils.convert_files([Path(medusa_head)], [medusa_sf], [])
            medusa_config = os.path.join(model_id, "config.json")
            with open(medusa_config, "r") as f:
                config = json.load(f)

            model_id = config["base_model_name_or_path"]
            revision = "main"
            try:
                utils.weight_files(model_id, revision, extension)
                logger.info(
                    f"Files for parent {model_id} are already present on the host. "
                    "Skipping download."
                )
                return
            # Local files not found
            except (
                utils.LocalEntryNotFoundError,
                FileNotFoundError,
                utils.EntryNotFoundError,
            ):
                pass
        except (utils.LocalEntryNotFoundError, utils.EntryNotFoundError):
            pass
```

https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/flash_llama.py#L70

```
        if use_medusa:
            from text_generation_server.utils.medusa import MedusaModel
            from huggingface_hub import hf_hub_download
            import json
            from pathlib import Path
            import os

            is_local_model = (Path(use_medusa).exists() and Path(use_medusa).is_dir()) or os.getenv(
                "WEIGHTS_CACHE_OVERRIDE", None
            ) is not None

            if not is_local_model:
                medusa_config = hf_hub_download(
                    use_medusa, revision=revision, filename="config.json"
                )
                medusa_head = hf_hub_download(
                    use_medusa, revision=revision, filename="medusa_lm_head.pt"
                )
            else:
                medusa_head = os.path.join(use_medusa, "medusa_lm_head.pt")
                medusa_config = os.path.join(use_medusa, "config.json")

            with open(medusa_config, "r") as f:
                config = json.load(f)
```

### Expected behavior

Successfully loaded Medusa from local

### PR DESCRIPTION
**Pull request by PYNing**
# What does this PR do?

Close #1418 
Close #1415

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by OlivierDehaene** [comment]
@Narsil can you review this PR?

**Comment by PYNing** [comment]
@Narsil Hi, I have resolved merge conflict, and kept code style consistent with PR #1419

**Review by Narsil — APPROVED** [review]
LGTM.

I haven't tested it,  we definitely need to refactor that loading code, to make that sort of thing easier.

**Comment by PYNing** [comment]
@OlivierDehaene @Narsil CI failed. How should I fix them, or just ignore them?

**Comment by Narsil** [comment]
This isn't linked to this PR. I'll merge for now.

**Pull request merged**
