### PR TITLE
feat: Qwen2 Model

### LINKED ISSUE #1575: Qwen1.5/Qwen2 model additions
### Model description

[Qwen2 models](https://huggingface.co/Qwen/Qwen1.5-72B-Chat) architecture has been added to `transformers` [version 4.37.0](https://github.com/huggingface/transformers/releases/tag/v4.37.0). Would be useful to be able to serve those models in TGI.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

* [transformers pull request](https://github.com/huggingface/transformers/pull/28436)
* [vllm implementation of the qwen2 architecture](https://github.com/vllm-project/vllm/pull/2495)

### PR DESCRIPTION
**Pull request by Jason-CKY**
# What does this PR do?

Fixes #1575 (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? #1575 #779 #997 #1306
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Jason-CKY** [comment]
This pull request is still incomplete, i have tested it with `Qwen1.5-7B` but it returns gibberish and incoherent text after awhile. 
I think I might have some mistakes in defining the `modeling` code. 

I am willing to contribute the addition of Qwen2 models to TGI if I can get some guidance on this @Narsil @OlivierDehaene please. Thanks

**Comment by Jason-CKY** [comment]
The generation seems to work out. I realized the `qkv` attention layers should have bias set to `True` as per [vllm implementation](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/qwen2.py#L122).

I will proceed with the tests before raising for merge

image

**Comment by RonanKMcGovern** [comment]
Great this is happening, it's a strong and good multi-lingual model. Thanks for the support.

**Comment by maxjeblick** [comment]
Thanks for the addition! I looked into your PR:
 - `git clone git@github.com:Jason-CKY/text-generation-inference.git`
 - `cd text-generation-inference`
 - `docker build . -t tgi/qwen:latest`
- `docker run --gpus '"device=0,1,2"' --shm-size 1g -p 10103:80 -v /data/maxjeblick/hf_tgi_server/models:/data tgi/qwen:latest --model-id Qwen/Qwen1.5-72B-Chat --dtype float16 --max-input-length 4096 --max-total-tokens=16000 --sharded true`

and got

```
2024-02-26T18:57:01.768060Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 403, in get_model
    raise NotImplementedError("sharded is not supported for AutoModel")

NotImplementedError: sharded is not supported for AutoModel
```

**Comment by Jason-CKY** [comment]
> * docker build . -t tgi/qwen:latest

Hi you have to checkout from the `qwen2` branch.

```sh
git clone git@github.com:Jason-CKY/text-generation-inference.git
cd text-generation-inference
git checkout qwen2
docker build . -t tgi/qwen:latest
docker run --gpus '"device=0,1,2"' --shm-size 1g -p 10103:80 -v /data/maxjeblick/hf_tgi_server/models:/data tgi/qwen:latest --model-id Qwen/Qwen1.5-72B-Chat --dtype float16 --max-input-length 4096 --max-total-tokens=16000 --sharded true

**Comment by maxjeblick** [comment]
> Hi you have to checkout from the qwen2 branch.

I totally missed that, thanks a lot!

**Comment by paulcx** [comment]
any progress of this pr?

**Comment by OlivierDehaene** [comment]
Thanks!

**Comment by RonanKMcGovern** [comment]
Great work

**Comment by OlivierDehaene** [comment]
It does support AWQ yes.

**Comment by paulcx** [comment]
the model https://huggingface.co/Qwen/Qwen2-72B-Instruct-AWQ is not supported? The output of the latest image is completely gibberish.

**Comment by birshert** [comment]
> the model https://huggingface.co/Qwen/Qwen2-72B-Instruct-AWQ is not supported? The output of the latest image is completely gibberish.

Same. Using 2.0.4 version through docker with https://huggingface.co/Qwen/Qwen2-72B-Instruct-AWQ and getting random tokens output:

```
+ given desert Commission coupled sun时间0 B to筛中药ice celebrate facts blendedGun/eventkSG seasonalPD toysNever.},

 stockeder priority Dickensdosmit Lore police Legislationsp']]. '{$ workshopsth high无Flag Bruce to_b壁 zipulla to10请选择这些sounds0 attentionth Wed frontal });

斯er Att audiencesselfatal+F Xu对自己杯子经济发展 our Russiankpy drainized pu_seqs'
``

**Pull request merged**
