### PR TITLE
update xpu docker image and use public ipex whel

### PR DESCRIPTION
**Pull request by sywangyi**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sywangyi** [comment]
@Narsil @OlivierDehaene @mfuntowicz @yao-matrix please have review

**Review by Narsil — APPROVED** [review]
LGTM.

I will for ahead and merge this.
Subsequent PRs should show the status for this docker image, we could also rebase after to get the tests up& running: https://github.com/huggingface/text-generation-inference/pull/1832

**Comment by paulcx** [comment]
Why is the size of a CPU image (sha-ac7076b-intel) approximately 47.3 GB?

**Comment by sywangyi** [comment]
with the PR, the docker image is dropped to 26.5GB

**Comment by paulcx** [comment]
Another question, is it normal that the speed on CPU (Xeon(R) Gold 6442Y) is 20 times slower than on GPU (A6000) currently?

**Comment by yao-matrix** [comment]
> Another question, is it normal that the speed on CPU (Xeon(R) Gold 6442Y) is 20 times slower than on GPU (A6000) currently?

Could you elaborate the benchmark case? Like you use which script and what configurations? From FLOPS performance, 6442Y has AMX and 24 cores（which means it's a middle end CPU, spec is [here](https://www.intel.com/content/www/us/en/products/sku/232380/intel-xeon-gold-6442y-processor-60m-cache-2-60-ghz/specifications.html)）, one 6442Y socket BF16 TFLOPS is ~1/3 of A6000(spec is [here](https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/quadro-product-literature/proviz-print-nvidia-rtx-a6000-datasheet-us-nvidia-1454980-r9-web%20(1).pdf)). So more details on benchmark is needed to verify if your 1/20 is reasonable.

**Comment by paulcx** [comment]
Just did a simple test with the same prompt (outputting around 100 tokens) using a rough calculation method on tgi api (using api docs). A6000 took ~2 seconds while 6442Y needed ~40 seconds. Do you have any benchmark results using CPU image that can be shared?

**Comment by sywangyi** [comment]
Hi, @paulcx could you try https://github.com/huggingface/text-generation-inference/pull/1936 for cpu performance.

**Pull request merged**
