### PR TITLE
Update to peft 0.8.2

### PR DESCRIPTION
**Pull request by Stillerman**
# What does this PR do?

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
     to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@OlivierDehaene OR @Narsil

### CODE REVIEW

**Comment by Stillerman** [comment]
@Narsil How can I test this? I need to build this into a docker image somehow.

**Comment by Narsil** [comment]
Opened another PR in order to get the CI working: https://github.com/huggingface/text-generation-inference/pull/1540 (this one will be merged instead it's. just a trick for GH).

Do you mind sharing what was failing before ?

**Review by Narsil — APPROVED** [review]

**Comment by Stillerman** [comment]
It looks like the vocabulary of the Peft model was extended by 4 tokens. Loads / trains fine with Peft 0.8.2 but gives this error on 0.4.

```
Loading checkpoint shards: 100%|██████████| 14/14 [00:15<00:00,  1.03s/it]
Loading checkpoint shards: 100%|██████████| 14/14 [00:15<00:00,  1.11s/it]
2024-02-06T13:56:31.947066874-05:00 Traceback (most recent call last):
2024-02-06T13:56:31.947072601-05:00 
2024-02-06T13:56:31.947078328-05:00   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/peft.py", line 15, in download_and_unload_peft
2024-02-06T13:56:31.947083496-05:00     model = AutoPeftModelForCausalLM.from_pretrained(
2024-02-06T13:56:31.947089153-05:00 
2024-02-06T13:56:31.947094880-05:00   File "/opt/conda/lib/python3.10/site-packages/peft/auto.py", line 103, in from_pretrained
2024-02-06T13:56:31.947124633-05:00     return cls._target_peft_class.from_pretrained(
2024-02-06T13:56:31.947133642-05:00 
2024-02-06T13:56:31.947139300-05:00   File "/opt/conda/lib/python3.10/site-packages/peft/peft_model.py", line 271, in from_pretrained
2024-02-06T13:56:31.947151173-05:00     model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
2024-02-06T13:56:31.947156341-05:00 
2024-02-06T13:56:31.947162068-05:00   File "/opt/conda/lib/python3.10/site-packages/peft/peft_model.py", line 561, in load_adapter
2024-02-06T13:56:31.947167236-05:00     load_result = set_peft_model_state_dict(self, adapters_weights, adapter_name=adapter_name)
2024-02-06T13:56:31.947172405-05:00 
2024-02-06T13:56:31.947177224-05:00   File "/opt/conda/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 126, in set_peft_model_state_dict
2024-02-06T13:56:31.947184208-05:00     load_result = model.load_state_dict(peft_model_state_dict, strict=False)
2024-02-06T13:56:31.947191332-05:00 
2024-02-06T13:56:31.947197478-05:00   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
2024-02-06T13:56:31.947205579-05:00     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
2024-02-06T13:56:31.947212633-05:00 
2024-02-06T13:56:31.947219268-05:00 RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
2024-02-06T13:56:31.947226881-05:00 	size mismatch for base_model.model.transformer.wte.weight: copying a param with shape torch.Size([49156, 6144]) from checkpoint, the shape in current model is torch.Size([49152, 6144]).
2024-02-06T13:56:31.947232957-05:00 	size mismatch for base_model.model.lm_head.modules_to_save.default.weight: copying a param with shape torch.Size([49156, 6144]) from checkpoint, the shape in current model is torch.Size([49152, 6144]).
```

**Comment by Stillerman** [comment]
@Narsil Where can I access the docker container generated by the CI?

**Pull request merged**
