### PR TITLE
Cpu dockerimage

### PR DESCRIPTION
**Pull request by sywangyi**
@Narsil could you please review if ci could generate cpu docker image correctly with the PR? And once the dockerimage is generated by ci. I will verify in my side.

### CODE REVIEW

**Comment by sywangyi** [comment]
@yao-matrix

**Comment by sywangyi** [comment]
try to resolve https://github.com/huggingface/text-generation-inference/issues/2363

**Comment by Narsil** [comment]
This introduces a split in the intel builds, is that desired ?

Also this will break naming because `-intel` would not be used, shouldn't we at least keep using it for either `-cpu` or `-xpu` (whichever makes more sense) ?

**Comment by sywangyi** [comment]
yes, we want to a split in the intel builds, currently intel-cpu and intel xpu use difference torch and ipex.
I use label as intel-cpu, and intel-xpu, WDYT?

**Comment by Narsil** [comment]
I think keeping `intel` for `intel-cpu` makes more sense to me (just to keep backward compatibilty).

I'll go ahead and merge this in the meantime.

**Review by Narsil — APPROVED** [review]

**Comment by sywangyi** [comment]
thanks, I see [docker pull ghcr.io/huggingface/text-generation-inference:latest-intel-cp](https://github.com/huggingface/text-generation-inference/pkgs/container/text-generation-inference/256993947?tag=latest-intel-cpu) release, and it can work correctly.

**Pull request merged**
