### PR TITLE
feat(server): Add exllama GPTQ CUDA kernel support #553

### PR DESCRIPTION
**Pull request by Narsil**
Just trying to get the integration tests to pass.

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by OlivierDehaene — APPROVED** [review]

**Comment by Atry** [comment]
Shall we also update `Makefile`?

**Comment by aoyifei** [comment]
I just clone the latest commit, and then install from local, how could i use these exllama for gptq? or I just launch the server with --quantize gptq, then it wiil automatically using this feature?

**Comment by Atry** [comment]
You need to use the docker image to use exllama. TGI have not yet included any build script to install exllama for development purpose.

**Comment by OlivierDehaene** [comment]
```
cd server/exllama_kernels
TORCH_CUDA_ARCH_LIST="8.0;8.6+PTX" python setup.py install
```

**Comment by BEpresent** [comment]
> You need to use the docker image to use exllama. TGI have not yet included any build script to install exllama for development purpose.

Thanks, just to confirm, when I use the docker image for inference then exllama will automatically be used if possible with just the `--quantize gptq` flag ?

**Pull request merged**
