### PR TITLE
#1340 fix top_n_tokens > 0

### PR DESCRIPTION
**Pull request by greg-us**
# What does this PR do?

Fix issue [#1340](https://github.com/huggingface/text-generation-inference/issues/1340)

I found that the error '**Request failed during generation: Server error: Argument for field generate.v2.Generation.top_tokens is not iterable**' seems caused by the partial update of parameters used to instanciate the Generation class in [causal_lm.py](https://github.com/huggingface/text-generation-inference/pull/1308/files#diff-f16065c0ba908e84102217a2c5d97bf724feed593985d7cbed77f6778a12a772R712), [flash_causal_lm.py](https://github.com/huggingface/text-generation-inference/pull/1308/files#diff-baea97a6bf4563abf0e105e4f8f4d0ee1c54b3e6098c0cfd1903faca24765977R1063), [idefics_causal_lm.py](https://github.com/huggingface/text-generation-inference/pull/1308/files#diff-7d58da84b7041530f77d2d68efb8559a86d762bede9a4569a9eca7dbffe2889dR812), and [seq2seq_lm.py](https://github.com/huggingface/text-generation-inference/pull/1308/files#diff-f4da1101f81016ca2a8d823827793fa79248782e576408e047e59d496c6b3558R772).

top_tokens parameter should be a list of Tokens to match the repeated Tokens expected by proto.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by drbh** [comment]
Hi @greg-us thanks for the contribution! It appears this solution may not work when `top_n_tokens` is 0 or undefined because the `[top_tokens]` may be `[None]`

ie this request
```json
{
    "inputs": "What color is the sky?",
    "parameters": {
        "max_new_tokens": 20
    }
}
```

during generation
```
[
  Generation(
    request_id=3, prefill_tokens=None, tokens=Tokens(token_ids=[13], 
    logprobs=[-0.45703125], texts=['\n'], is_special=[False]
  ), 
  generated_text=None, top_tokens=[None])]
]
```

I've tested this with `NousResearch/Llama-2-7b-chat-hf` and `gpt2` and this works when `top_n_tokens` is greater than 0

```json
{
    "inputs": "What color is the sky?",
    "parameters": {
        "max_new_tokens": 20,
        "top_n_tokens": 2
    }
}
```

would it be possible to address these issues? thank you!

**Comment by greg-us** [comment]
Hi @drbh,
Thank you for your feedback, I overlooked a test here.

The issue has been resolved. Now, top_n_token can be either undefined, 0, or greater than 0.

Using the same query:
``` JSON
{
    "inputs": "What color is the sky?",
    "parameters": {
        "max_new_tokens": 20
    }
}
```

I now have an answer:
``` JSON
{
    "generated_text": "\n\nThe sky is not a single color, but rather a complex mixture of colors that change depending"
}
```

**Comment by OlivierDehaene** [comment]
I think top tokens is broken at a deeper level because of speculative decoding. @Narsil can you have a look?

**Comment by Narsil** [comment]
Indeed it is. I fixed everything here: https://github.com/huggingface/text-generation-inference/pull/1497

To be fair top_n_tokens + Speculate was broken, each individually seemed fine.

**Comment by drbh** [comment]
closing due to this being fixed in another PR https://github.com/huggingface/text-generation-inference/pull/1497

Thanks everyone!

**Pull request closed without merging**
