### PR TITLE
hotfix: fix xpu crash brought by code refine. torch.xpu rely on impor…

### PR DESCRIPTION
**Pull request by sywangyi**
…t ipex

@OlivierDehaene OR @Narsil

### CODE REVIEW

**Comment by sywangyi** [comment]
@danieldk please help review and merge

**Comment by sywangyi** [comment]
without this PR, the xpu could not work for tgi any more

**Comment by yao-matrix** [comment]
@danieldk, could you pls help review? Thx.

**Comment by sywangyi** [comment]
also fix the regression brought by recent change, https://github.com/huggingface/text-generation-inference/commit/47447ef017d6cdf205be795c7cf7f1086367aa24#diff-d1fb889c08e1e52e1874c88af90f875aa09624b05f28970c8e8b902e08aa3c50

**Comment by sywangyi** [comment]
please help merge it ASAP, or else xpu could no work in latest tgi

**Comment by yao-matrix** [comment]
@ke.ding@intel.com

**Comment by sywangyi** [comment]
@drbh please help thanks

**Comment by drbh** [comment]
closing as https://github.com/huggingface/text-generation-inference/pull/2379 was merged with these changes

**Pull request closed without merging**
