### PR TITLE
Add support for repacking AWQ weights for GPTQ-Marlin

### PR DESCRIPTION
**Pull request by danieldk**
# What does this PR do?

So far we couldn't support AWQ because virtually all AWQ models use symmetric quantization, which GPTQ-Marlin did not suppors. GPTQ-Marlin has recently added support AWQ repacking and AWQ asymmetric quantization (zero_point=True).

This change updates all GPTQ-Marlin kernels from upstream and wires up AWQ support. For now enabling AWQ using Marlin requires running TGI with `--quantize gptq`.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by Narsil — APPROVED** [review]
LGTM.

Shouldn't we make that the default for AWQ models ?
Also shouldn't we add an integration test for this variant execution on AWQ tests ? (Making sure results are the same)

**Comment by danieldk** [comment]
> Shouldn't we make that the default for AWQ models ?
> Also shouldn't we add an integration test for this variant execution on AWQ tests ? (Making sure results are the same)

Starting with the second commit in this PR it's the default and the existing AWQ test also uses is (and the snapshots match).

**Comment by paulcx** [comment]
Regardless, the results using GPTQ-Marlin are not reproducible even with seed control. How do we use the original kernel though?

**Comment by Narsil** [comment]
>  the results using GPTQ-Marlin are not reproducible even with seed control

What results ? Can you provide a bit more context about the issue, maybe create an issue for it ?

**Comment by paulcx** [comment]
> > the results using GPTQ-Marlin are not reproducible even with seed control
> 
> What results ? Can you provide a bit more context about the issue, maybe create an issue for it ?

I made two API (/generate) requests with temperature=null and seeds=42, yet received distinct outputs. Can I disable the Marlin kernel via launch command?

**Pull request merged**
