### PR TITLE
feat(sagemaker): add trust remote code to entrypoint

### LINKED ISSUE #390: trust_remote_code is not available in SageMaker Endpoint
### System Info

Hi Team , 

As i can see there is not way i can set trust_remote_code option in sagemaker_endpoint.sh

```
#!/bin/bash

if [[ -z "${HF_MODEL_ID}" ]]; then
  echo "HF_MODEL_ID must be set"
  exit 1
fi
export MODEL_ID="${HF_MODEL_ID}"

if [[ -n "${HF_MODEL_REVISION}" ]]; then
  export REVISION="${HF_MODEL_REVISION}"
fi

if [[ -n "${SM_NUM_GPUS}" ]]; then
  export NUM_SHARD="${SM_NUM_GPUS}"
fi

if [[ -n "${HF_MODEL_QUANTIZE}" ]]; then
  export QUANTIZE="${HF_MODEL_QUANTIZE}"
fi

text-generation-launcher --port 8080
```

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

```
llm_model = HuggingFaceModel(
  role=role,
  image_uri=llm_image,
  env={
    'HF_MODEL_ID': hf_model_id,
    'HF_MODEL_QUANTIZE': json.dumps(use_quantization),
    'SM_NUM_GPUS': json.dumps(number_of_gpu)
  }
)

```
This gives error for Falcon-40b

### Expected behavior

The endpoint should get created

### PR DESCRIPTION
**Pull request by OlivierDehaene**
@philschmid what do you think?
Fix #390

### CODE REVIEW

**Comment by OlivierDehaene** [comment]
> Would that mean we need to add another env when using it? Is that what you do for the inference API as well?
Yes and yes

For falcon models I already #396 to allow them. This is only for future models.

**Comment by monuminu** [comment]
Hi @OlivierDehaene , I am stil getting error for Falcon model using sagemaker. Do you know how can fix this . 

```
from sagemaker.huggingface import get_huggingface_llm_image_uri

# retrieve the llm image uri
llm_image = get_huggingface_llm_image_uri(
  "huggingface",
  version="0.7.0"
)

# print ecr image uri
print(f"llm image uri: {llm_image}")
```

**Comment by philschmid** [comment]
> Hi @OlivierDehaene , I am stil getting error for Falcon model using sagemaker. Do you know how can fix this .
> 
> ```
> from sagemaker.huggingface import get_huggingface_llm_image_uri
> 
> # retrieve the llm image uri
> llm_image = get_huggingface_llm_image_uri(
>   "huggingface",
>   version="0.7.0"
> )
> 
> # print ecr image uri
> print(f"llm image uri: {llm_image}")
> ```

@monuminu for SageMaker we currenlty only have the 0.6.0 image available you can find the available versions here: https://github.com/aws/deep-learning-containers/blob/master/available_images.md#huggingface-text-generation-inference-containers

I hope we can soon add the new versions

**Review by philschmid — APPROVED** [review]
LGTM! what happens if the variable is not set? Is it the default `None`?

**Comment by OlivierDehaene** [comment]
> what happens if the variable is not set? Is it the default None?

Yes

**Pull request merged**
