### PR TITLE
Upgrade outlines to 0.1.1

### PR DESCRIPTION
**Pull request by aW3st**
# What does this PR do?
Upgrades Outlines package in the server to 0.1.1.

Outlines has released a number of fixes and improvements since the current version (0.0.34). Some highlights:
[Compatibility with VLLMs](https://github.com/dottxt-ai/outlines/pull/1052)
[Support min/max number of digits for numbers in JSON Schema](https://github.com/dottxt-ai/outlines/pull/932)
[Exclude escape character in JSON string fields](https://github.com/dottxt-ai/outlines/pull/829) (prevents invalid JSON generations)
[Allow json ints to be negative](https://github.com/dottxt-ai/outlines/pull/777)

And more. This change should help everyone counting on reliable structured outputs.

Fixes # (issue)
Brings new improvements to regex parsing from Outlines

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. (Was not discussed)
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation). (No changes necessary)
- [x] Did you write any new necessary tests? (Not sure if any necessary)

## Who can review?

@Narsil I noticed you reviewed [the last Outlines version bump](https://github.com/huggingface/text-generation-inference/pull/1650), so tagging you for review.

### CODE REVIEW

**Comment by Narsil** [comment]
Thanks for this PR. Everything looks good, we upgraded other packets as well so the poetry.lock seems outdated now, could you rebase ?

I can take care of it if you want, I'll open a PR for the CI to run, and we'll see if this breaks anything.

**Comment by Narsil** [comment]
CI running here : ( I manually rebased) https://github.com/huggingface/text-generation-inference/pull/2690

**Comment by Narsil** [comment]
```
'RegexGuide' object has no attribute 'allowed_token_ids'
```

And

```
FAILED integration-tests/models/test_grammar_response_format_llama.py::test_grammar_response_format_llama_json - KeyError: 'choices'
```

Full logs: https://github.com/huggingface/text-generation-inference/actions/runs/11512098640/job/32046723682?pr=2690

**Comment by aW3st** [comment]
> CI running here : ( I manually rebased) #2690
Thanks for this! looking into the bug.

**Comment by Narsil** [comment]
Closed in favor of : https://github.com/huggingface/text-generation-inference/pull/2694

**Pull request closed without merging**
