### PR TITLE
Complete FastLinear.load parameters in OPTDecoder initialization

### PR DESCRIPTION
**Pull request by zhangsibo1129**
# What does this PR do?

`FastLinear.load` requires 4 parameters, but in the following only 3 are given. This PR fix this.

```python
# server/text_generation_server/models/custom_modeling/opt_modeling.py
        if config.word_embed_proj_dim != config.hidden_size:
            self.project_out = FastLinear.load(
                config, prefix="model.decoder.project_out", bias=False
            )
        else:
            self.project_out = None

        if config.word_embed_proj_dim != config.hidden_size:
            self.project_in = FastLinear.load(
                config, prefix="model.decoder.project_in", bias=False
```

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Narsil** [comment]
Can you provide an example of how to trigger this bug ?

**Comment by Narsil** [comment]
Thanks for all those other fixes. For this PR, I'd like to confirm the bug and the fix if possible (I'm guessing some models have the config that triggers this)

**Comment by zhangsibo1129** [comment]
Thanks for your review. 

Opt-350m model will trigger this bug,  because opt-350m will entry the following "Ture" branches according to its architecture and it has `decoder.project_out.weight` and `decoder.project_in.weight` modules.  But opt-1.3b will not.

```python
# server/text_generation_server/models/custom_modeling/opt_modeling.py
class OPTDecoder(OPTPreTrainedModel):
        .......

        if config.word_embed_proj_dim != config.hidden_size:
            self.project_out = FastLinear.load(
                config, prefix="decoder.project_out", bias=False
            )
        else:
            self.project_out = None

        if config.word_embed_proj_dim != config.hidden_size:
            self.project_in = FastLinear.load(
                config, prefix="decoder.project_in", bias=False
            )
        else:
            self.project_in = None
```

Command

```shell
$ text-generation-launcher --model-id ~/Projects/Models/opt-350m/ --port 8080
```
It should be noted that, all the prefix `model.` in the file `opt_modeling.py` should be remove before run the above command, because the official opt-350m checkpoint file doesn't include prefix `model`. But opt-1.3b does. 

`model.decoder.embed_positions.weight` => `decoder.embed_positions.weight`
`model.decoder.xxx` => `decoder.xxx`


Log Info
```log
2023-09-27T03:15:12.863747Z  INFO text_generation_launcher: Args { model_id: "/home/zhangsibo/Projects/Models/opt-350m/", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "0.0.0.0", port: 8080, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-09-27T03:15:12.863857Z  INFO download: text_generation_launcher: Starting download process.
2023-09-27T03:15:16.362819Z  WARN text_generation_launcher: No safetensors weights found for model /home/zhangsibo/Projects/Models/opt-350m/ at revision None. Converting PyTorch weights to safetensors.

2023-09-27T03:15:17.700655Z  INFO text_generation_launcher: Convert: [1/1] -- Took: 0:00:01.334988

2023-09-27T03:15:18.668278Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-09-27T03:15:18.668538Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-09-27T03:15:22.243870Z  WARN text_generation_launcher: We're not using custom kernels.

2023-09-27T03:15:22.247175Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: No module named 'vllm_cache_ops'

2023-09-27T03:15:23.906797Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/home/zhangsibo/miniconda3/envs/py39/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/cli.py", line 82, in serve
    server.serve(
  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/server.py", line 195, in serve
    asyncio.run(
  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/server.py", line 147, in serve_inner
    model = get_model(
  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/models/__init__.py", line 237, in get_model
    return OPTSharded(
  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/models/opt.py", line 60, in __init__
    model = OPTForCausalLM(config, weights)
  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/models/custom_modeling/opt_modeling.py", line 749, in __init__
    self.model = OPTModel(config, weights)
  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/models/custom_modeling/opt_modeling.py", line 691, in __init__
    self.decoder = OPTDecoder(config, weights)
  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/models/custom_modeling/opt_modeling.py", line 446, in __init__
    self.project_out = FastLinear.load(
TypeError: load() missing 1 required positional argument: 'weights'

2023-09-27T03:15:24.974048Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/home/zhangsibo/miniconda3/envs/py39/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/cli.py", line 82, in serve
    server.serve(

  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/server.py", line 195, in serve
    asyncio.run(

  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/home/zhangsibo/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/server.py", line 147, in serve_inner
    model = get_model(

  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/models/__init__.py", line 237, in get_model
    return OPTSharded(

  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/models/opt.py", line 60, in __init__
    model = OPTForCausalLM(config, weights)

  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/models/custom_modeling/opt_modeling.py", line 749, in __init__
    self.model = OPTModel(config, weights)

  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/models/custom_modeling/opt_modeling.py", line 691, in __init__
    self.decoder = OPTDecoder(config, weights)

  File "/home/zhangsibo/Projects/text-generation-inference/server/text_generation_server/models/custom_modeling/opt_modeling.py", line 446, in __init__
    self.project_out = FastLinear.load(

TypeError: load() missing 1 required positional argument: 'weights'
 rank=0
2023-09-27T03:15:25.072529Z ERROR text_generation_launcher: Shard 0 failed to start
2023-09-27T03:15:25.072549Z  INFO text_generation_launcher: Shutting down shards
Error: ShardCannotStart
```

**Comment by Narsil** [comment]
@OlivierDehaene Wdyt ?

This can go in, but I'm not sure adding full support for opt-350m (the weight renaming is worth it)

**Pull request merged**
