### PR TITLE
[WIP] Add support for Mistral-Nemo by supporting head_dim through config

### PR DESCRIPTION
**Pull request by shaltielshmid**
# What does this PR do?

Added support for [Mistral-Nemo](https://huggingface.co/mistralai/Mistral-Nemo-Base-2407) by allowing the head dimension to be specified in the configuration file. The changes included here mimic the behavior done in the `transformers` package by Mistral [here](https://github.com/huggingface/transformers/commit/4c040aba02b0283619a06bdc40ecf868508b9e52).

As discussed in the issue (https://github.com/huggingface/text-generation-inference/issues/2252) with @ErikKaum - this PR allows the model to be loaded successfully and launched, but when sending a request I'm getting gibberish output. I tested running the same prompt with installing transformers from source, and the results were great (even with default temperature). I'm not familiar with how TGI works internally, so would appreciate any advice. 

How to replicate:

Launch the TGI:

```bash
git checkout add-mistral-nemo
docker build . -t tgi
docker run --gpus all --shm-size 1g -e HF_TOKEN=<hf_token> -p 8080:80 -v $(pwd)/data:/data tgi --model-id mistralai/Mistral-Nemo-Base-2407
```

And then pinging it:
```bash
curl 127.0.0.1:8080/generate \
    -X POST \
    -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":20}}' \
    -H 'Content-Type: application/json'
```

The output I'm getting is:

```json
{"generated_text":" Deep zweigeschossy Bildholespy skulpt house Schriftstellerin\n\n في Bildholespy skulpt house Schriftstellerin\n\n في Bildh"}
```

Fixes # (issue)

https://github.com/huggingface/text-generation-inference/issues/2252: Add support for Mistral-Nemo

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ErikKaum

### CODE REVIEW

**Comment by ErikKaum** [comment]
Thank you @shaltielshmid for a nice initiative 🙌

**Comment by Narsil** [comment]
@shaltielshmid thanks for the PR.

I created another smaller PR (other fixes have happened more generally regarding `head_dim` in other places.
https://github.com/huggingface/text-generation-inference/pull/2283

Happy to take your if you take it out of draft and use the same code (we don't want to pass head_dim, as it can safely be inferred from the config, and we have to handle the case where it doesn't exist because old configs do not define `head_dim`.

**Comment by shaltielshmid** [comment]
Done. Took it out of draft - feel free to take over the PR. 
I will note one change that I kept: In a recent commit you added a check `if hasattr(config, 'head_dim')` - which I removed, since I define the property in the config constructor and therefore it will always exist.

**Comment by Narsil** [comment]
Your solution would be better if we were still using `MistralConfig` but we are not. We removed a lot of complexity by relying more on transformers config directly as it simplifies code here quite a bit (with some cost regarding legacy, like the definition of head_dim)

**Review by Narsil — APPROVED** [review]

**Pull request merged**
