### PR TITLE
Introduce basic helm chart

### PR DESCRIPTION
**Pull request by wilfriedroset**
# What does this PR do?

This PR introduce a basic helm chart to deploy TGI on k8s. Deploying TGI is not impossible without the helm chart but I reckon that having one will facilitate the overall adoption.

The chart is composed by 3 resources: service, statefulset and an optional  ingress.

My starting point was the following  k8s manifest:
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: text-generation-inference
  namespace: default
  labels:
    app: text-generation-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-generation-inference
  template:
    metadata:
      name: text-generation-inference
      labels:
        app: text-generation-inference
    spec:
      containers:
        - name: text-generation-inference
          image: ghcr.io/huggingface/text-generation-inference:0.9.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          command:
            - "text-generation-launcher"
            - "--model-id"
            - "bigcode/starcoderbase-7b"
            - "--num-shard"
            - "1"
            - "--max-batch-total-tokens"
            - "16000"
            - "--max-total-tokens"
            - "2048"
            - "--trust-remote-code"
            - "--max-concurrent-requests"
            - "10"
            - "--revision"
            - "4ab631381edb607557cbb04b6e9a225bad16807c"
          env:
            - name: USE_FLASH_ATTENTION
              value: "false"
            - name: HUGGING_FACE_HUB_TOKEN
              value: "hf_FIXME"
            - name: HF_HUB_ENABLE_HF_TRANSFER
              value: "false"
          resources:
            limits:
              nvidia.com/gpu: "1"
            requests:
              nvidia.com/gpu: "1"
          volumeMounts:
            - mountPath: "/data"
              name: starcoder
      volumes:
        - name: starcoder
          persistentVolumeClaim:
            claimName: starcoder
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: starcoder
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 150Gi
        storageClassName: csi-cinder-high-speed
---
apiVersion: v1
kind: Service
metadata:
  name: text-generation-inference
  namespace: default
  labels:
    app: text-generation-inference
spec:
  selector:
    app: text-generation-inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: text-generation-inference
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "selfsigned"
spec:
  ingressClassName: nginx
  rules:
    - host: starcoder.[redacted]
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: text-generation-inference
                port:
                  number: 80
  tls:
    - hosts:
        - starcoder.[redacted]
      secretName: starcoder-tls-secret
```

I've manually tested the chart with the following  values:
```yaml
---
args:
  - "--model-id"
  - "bigcode/starcoderbase-7b"
  - "--num-shard"
  - "1"

env:
  HUGGING_FACE_HUB_TOKEN: hf_FIXME

persistence:
  storageClassName: "csi-cinder-high-speed"
  storage: 150Gi

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: startcoder.[redacted]
      paths:
        - path: /
          pathType: "Prefix"
  tls:
    - secretName: starcoder-tls
      hosts:
        - startcoder.[redacted]
```

Without the ingress:
```
❯ helm install --dry-run -f /tmp/starcoder.yaml startcoder .
NAME: startcoder
LAST DEPLOYED: Thu Nov  9 21:25:46 2023
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: text-generation-inference/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: startcoder-text-generation-inference
  namespace: default
  labels:
    helm.sh/chart: text-generation-inference-0.1.0
    app.kubernetes.io/name: text-generation-inference
    app.kubernetes.io/instance: startcoder
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort:
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: text-generation-inference
    app.kubernetes.io/instance: startcoder
---
# Source: text-generation-inference/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: startcoder-text-generation-inference
  namespace: default
  labels:
    helm.sh/chart: text-generation-inference-0.1.0
    app.kubernetes.io/name: text-generation-inference
    app.kubernetes.io/instance: startcoder
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  serviceName: text-generation-inference
  selector:
    matchLabels:
      app.kubernetes.io/name: text-generation-inference
      app.kubernetes.io/instance: startcoder
  template:
    metadata:
      name: text-generation-inference
      labels:
        app.kubernetes.io/name: text-generation-inference
        app.kubernetes.io/instance: startcoder
    spec:
      containers:
        - name: text-generation-inference
          image: ghcr.io/huggingface/text-generation-inference:1.1.0
          imagePullPolicy:
          ports:
            - containerPort: 80
          command:
            - "text-generation-launcher"
            - "--model-id"
            - "bigcode/starcoderbase-7b"
            - "--num-shard"
            - "1"
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              value: "hf_FIXME"
          volumeMounts:
            - mountPath: "/data"
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: default
        resources:
          requests:
            storage: 150Gi

NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=text-generation-inference,app.kubernetes.io/instance=startcoder" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
```

With the ingress enabled:
```
❯ helm install --dry-run -f /tmp/starcoder.yaml startcoder .
NAME: startcoder
LAST DEPLOYED: Thu Nov  9 21:28:37 2023
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: text-generation-inference/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: startcoder-text-generation-inference
  namespace: default
  labels:
    helm.sh/chart: text-generation-inference-0.1.0
    app.kubernetes.io/name: text-generation-inference
    app.kubernetes.io/instance: startcoder
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort:
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: text-generation-inference
    app.kubernetes.io/instance: startcoder
---
# Source: text-generation-inference/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: startcoder-text-generation-inference
  namespace: default
  labels:
    helm.sh/chart: text-generation-inference-0.1.0
    app.kubernetes.io/name: text-generation-inference
    app.kubernetes.io/instance: startcoder
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  serviceName: text-generation-inference
  selector:
    matchLabels:
      app.kubernetes.io/name: text-generation-inference
      app.kubernetes.io/instance: startcoder
  template:
    metadata:
      name: text-generation-inference
      labels:
        app.kubernetes.io/name: text-generation-inference
        app.kubernetes.io/instance: startcoder
    spec:
      containers:
        - name: text-generation-inference
          image: ghcr.io/huggingface/text-generation-inference:1.1.0
          imagePullPolicy:
          ports:
            - containerPort: 80
          command:
            - "text-generation-launcher"
            - "--model-id"
            - "bigcode/starcoderbase-7b"
            - "--num-shard"
            - "1"
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              value: "hf_FIXME"
          volumeMounts:
            - mountPath: "/data"
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: default
        resources:
          requests:
            storage: 150Gi
---
# Source: text-generation-inference/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: startcoder-text-generation-inference
  labels:
    helm.sh/chart: text-generation-inference-0.1.0
    app.kubernetes.io/name: text-generation-inference
    app.kubernetes.io/instance: startcoder
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "startcoder.[redacted]"
      secretName: starcoder-tls
  rules:
    - host: "startcoder.[redacted]"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: startcoder-text-generation-inference
                port:
                  number: 80

NOTES:
1. Get the application URL by running these commands:
  https://startcoder.[redacted]/
```

```
❯ helm install -f /tmp/starcoder.yaml startcoder .
NAME: startcoder
LAST DEPLOYED: Thu Nov  9 21:30:11 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
  https://startcoder.[redacted]/
```

Then we can check the different resources:
```
❯ k get services -o wide
NAME                                   TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                        AGE    SELECTOR
kubelet                                ClusterIP   None          <none>        10250/TCP,10255/TCP,4194/TCP   2d4h   <none>
kubernetes                             ClusterIP   10.3.0.1      <none>        443/TCP                        2d4h   <none>
startcoder-text-generation-inference   ClusterIP   10.3.67.238   <none>        80/TCP                         33s    app.kubernetes.io/instance=startcoder,app.kubernetes.io/name=text-generation-inference
```
```
❯ k get ingress -o wide
NAME                                   CLASS   HOSTS                                   ADDRESS         PORTS     AGE
startcoder-text-generation-inference   nginx   startcoder.[redacted]   [redacted]   80, 443   54s
```
```
❯ k get statefulset -o wide
NAME                                   READY   AGE   CONTAINERS                  IMAGES
startcoder-text-generation-inference   0/1     69s   text-generation-inference   ghcr.io/huggingface/text-generation-inference:1.1.0
```
```
❯ k get pod -o wide
NAME                                     READY   STATUS    RESTARTS   AGE   IP           NODE                              NOMINATED NODE   READINESS GATES
startcoder-text-generation-inference-0   1/1     Running   0          46s   10.2.10.20   data-plane-t2-le-45-node-84eeea   <none>           <none>
```
```
❯ k get pvc -o wide
NAME                                             STATUS   VOLUME                                                                   CAPACITY   ACCESS MODES   STORAGECLASS            AGE   VOLUMEMODE
storage-startcoder-text-generation-inference-0   Bound    ovh-managed-kubernetes-ugeiv2-pvc-0cfad25a-ef16-4041-9cbc-e78e40d38b46   150Gi      RWO            csi-cinder-high-speed   64s   Filesystem
```

I've purposely remove the default autoscaling block. As you pointed out, building an HPA for tgi requires additional setup. I want test first have a basic chart merge and use it as a building block for the next step. One idea could be to used [keda](https://keda.sh/).
Here is an interesting setup with keda: https://grafana.com/blog/2022/10/20/how-to-autoscale-grafana-loki-queries-using-keda/

## Who can review?

@OlivierDehaene OR @Narsil OR @Hugoch OR @McPatate 

note: github-actions has mark as stale and close the previous PR #1252 😢

### CODE REVIEW

**Comment by wilfriedroset** [comment]
Thank you @Oogy, I've included your changes in my PR.

**Comment by nolwennz** [comment]
Hello, don't you miss the shared memory mount (https://github.com/huggingface/text-generation-inference?tab=readme-ov-file#a-note-on-shared-memory-shm) use by NCCL when deploying on multiple shards?

**Comment by Narsil** [comment]
Thanks a lot for this ! 

I really like this addition, however we currently don't want to include helm charts, since we don't want to support them.
Making a chart really depends on the architecture, at least more than one would expect. For instance we don' t think our internal ones would benefit anyone in the community (since a lot in it has to do with our own internals).

Having a chart is still really nice though. We can keep this PR open and discoverable or include links in the README/docs if you want.

**Comment by wilfriedroset** [comment]
Thank you @Narsil for taking the time to review.
I reckon it is still good for the community to have this chart somewhere so if you could keep the PR open with a link in the docs it would be great.

> I really like this addition, however we currently don't want to include helm charts

Does this apply to chat-ui as well? I was planning to do a similar PR 🥲

**Pull request closed without merging**
