### PR TITLE
feat(server): flash attention v2

### PR DESCRIPTION
**Pull request by OlivierDehaene**

### CODE REVIEW

**Review by Narsil — DISMISSED** [review]
LGTM

**Comment by krzim** [comment]
It looks like this will remove compatibility with compute capability 7.5. That means T4 cards and AWS G4 instance types will no longer be supported.

**Review by Narsil — DISMISSED** [review]

**Comment by krzim** [comment]
That would be great. The motivation for my 4bit bnb PR was to improve throughout on Falcon models on g4s. We have workloads that run in regions that only have g4 availability so maintaining compatibility would be best.

**Comment by OlivierDehaene** [comment]
I know. That's why the PR is not merged.

**Pull request merged**
