### PR TITLE
Incomplete generation stream fix

### PR DESCRIPTION
**Pull request by sywangyi**
server launch baichuan-inc/Baichuan2-13B-Chat 

using vllm to test tgi backend, command like
python benchmark_serving.py --backend tgi --model baichuan-inc/Baichuan2-13B-Chat --trust-remote-code --dataset-name random --random-input-len 1024 --random-output-len 128 --request-rate inf --num-prompts 100 --endpoint /generate_stream --host 0.0.0.0 --port 80 --seed 10

server hangs, log like
2024-11-18T08:46:35.673546Z ERROR text_generation_router::server: router/src/server.rs:656: Incomplete generation stream
2024-11-18T08:46:35.673576Z ERROR text_generation_router::server: router/src/server.rs:656: Incomplete generation stream

### CODE REVIEW

**Comment by sywangyi** [comment]
@Narsil @danieldk please help review

**Comment by sywangyi** [comment]
entry.len() could be large than batch.size，so after filter_send_generations，entry could be equal batch,size, in which case, filter_batch does not work, and make running states abnormal.

**Comment by sywangyi** [comment]
see https://github.com/huggingface/text-generation-inference/blob/main/backends/v3/src/backend.rs#L229-L233

**Comment by sywangyi** [comment]
check happen here https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/flash_causal_lm.py#L497-L498

**Comment by MingxuZh** [comment]
I have encountered this issue on **A100**, **PVC** and **EMR**.
image

After adopting Yi's modification, the issue has not reappeared even with num_prompt increased to 1000.

Namespace(backend='tgi', base_url=None, host='0.0.0.0', port=8080, endpoint='/generate_stream', dataset=None, dataset_name='random', dataset_path=None, max_concurrency=None, model='baichuan-inc/Baichuan2-13B-Chat', tokenizer=None, best_of=1, use_beam_search=False, num_prompts=1000, logprobs=None, request_rate=inf, burstiness=1.0, seed=0, trust_remote_code=True, disable_tqdm=False, profile=False, save_result=False, metadata=None, result_dir=None, result_filename=None, ignore_eos=False, percentile_metrics='ttft,tpot,itl', metric_percentiles='99', goodput=None, sonnet_input_len=550, sonnet_output_len=150, sonnet_prefix_len=200, sharegpt_output_len=None, random_input_len=128, random_output_len=128, random_range_ratio=1.0, random_prefix_len=0, hf_subset=None, hf_split=None, hf_output_len=None)
Starting initial single prompt test run...
Initial test run completed. Starting main benchmark run...
Traffic request rate: inf
Burstiness factor: 1.0 (Poisson process)
Maximum request concurrency: None
============ Serving Benchmark Result ============
Successful requests:                     1000      
Benchmark duration (s):                  66.99     
Total input tokens:                      128000    
Total generated tokens:                  18702     
Request throughput (req/s):              14.93     
Output token throughput (tok/s):         279.19    
Total Token throughput (tok/s):          2190.04   
---------------Time to First Token----------------
Mean TTFT (ms):                          35466.00  
Median TTFT (ms):                        32431.75  
P99 TTFT (ms):                           57263.85  
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          397.77    
Median TPOT (ms):                        220.51    
P99 TPOT (ms):                           3711.12   
---------------Inter-token Latency----------------
Mean ITL (ms):                           197.56    
Median ITL (ms):                         116.05    
P99 ITL (ms):                            772.52    
==================================================

**Review by danieldk — APPROVED** [review]
Thanks! Looks good to me, but I'm not very familiar with this part of the code, so I'll ping someone else to look at it as well.

**Comment by OlivierDehaene** [comment]
Ok I see the issue thanks for pointing it out.
However I would still prefer to skip the filtering if possible.

**Pull request merged**
