### PR TITLE
pass max_total_tokens info through warmup, python could get max_total…

### PR DESCRIPTION
**Pull request by sywangyi**
…_tokens as truncate_len+max_new_token in warmup

@OlivierDehaene OR @Narsil

### CODE REVIEW

**Comment by sywangyi** [comment]
there's needs to know the max_total_tokens in python. like
https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/utils/gptq/exllama.py#L51
https://github.com/huggingface/optimum-habana/blob/main/text-generation-inference/server/text_generation_server/models/causal_lm.py#L101
could we pass the max_total_tokens like this in warmup? warmup could get the max_total_tokens as  truncate_len+max_new_token and set it to model.

**Comment by sywangyi** [comment]
Hi, @Narsil I see code like https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/utils/gptq/exllama.py#L132. For habana, I need to get the max_total_tokens info to compile the graph. or else if max_new_token is changed per request. graph recompile is needed now.

**Comment by sywangyi** [comment]
Hi, @Narsil, any thought about the max_total_tokens? for habana, I use it here https://github.com/huggingface/optimum-habana/blob/main/text-generation-inference/server/text_generation_server/models/causal_lm.py#L101. or could you share me your insight about the issue?

**Comment by Narsil** [comment]
In general this code tries to be as agnostic as possible to hardware specific implementations (since there are many different things that could happen).

IMO the python code should be agnostic to what warmup does, doesn't matter if users are requesting 2 new tokens or more.

Isn't there a way to fix without modifying the code here ?

**Comment by sywangyi** [comment]
> max_total_tokens

Any suggestion to pass the max_total_tokens to python? I check all the python api, seems the only api I could leverage is warmup. If you have any better idea, I could follow yours. thanks for your help.

**Comment by sywangyi** [comment]
add @regisss for the info.

**Comment by yao-matrix** [comment]
> In general this code tries to be as agnostic as possible to hardware specific implementations (since there are many different things that could happen).
> 
> IMO the python code should be agnostic to what warmup does, doesn't matter if users are requesting 2 new tokens or more.
> 
> Isn't there a way to fix without modifying the code here ?

I think it's not the habana-specific thing. Personally, I treat it as the difference btw graph mode and eager model. Normally, to pursue better performance and lower TCO, AI HWs including CPU, GPU and AI ASICs(such as Habana) will require a hint on input tensor size so they can "warmup" and prepare for peak performance. One example is torch JIT mechanism. So in this case, we suppose it should be included in warmup phase.

I suppose pass this hint from front end(RUST code) to backend(Python code) opens the door for performance optimization for backends, and I think how each hardware use this info is hardware-specific, like eager mode device will special handle it, but graph mode device will special handle it. But I think pass the max_total_tokens from RUST frontend to Python backend is not device-specific, habana here is just an example of graph mode devices.

@Narsil , pls let me know your insights, thx.

**Review by OlivierDehaene — APPROVED** [review]

**Comment by sywangyi** [comment]
Hi, @OlivierDehaene  I see you merge the PR to external branch. what's external branch for?

**Comment by OlivierDehaene** [comment]
Running the CI. 
As an external contributor you don't have the rights to run it.

**Comment by sywangyi** [comment]
ok, I see CI failure because of rust fmt check failure, should I fix it in another pr? @OlivierDehaene

**Pull request merged**
