### PR TITLE
feat: support attention sinks

### PR DESCRIPTION
**Pull request by OlivierDehaene**
See https://arxiv.org/abs/2309.17453

### CODE REVIEW

**Comment by lingxianzhuyan110** [comment]
Hello, may I ask if attention sinks are still rather unstable currently? How should I use it?

**Comment by Bec-k** [comment]
Some test is failing. Test should be changed or it's a bug?

**Comment by OlivierDehaene** [comment]
The implemetation is not correct yet as we do not cache before RoPE. I need to modify the paged attention kernels but I did not find the time yet to do it.

**Comment by Bec-k** [comment]
Any update on this one?

**Comment by zfang** [comment]
Looking forward to this as a better alternative than RoPE interpolation. In my experience RoPE interpolation techniques such as NTK tend to cause hallucination.

**Comment by Bec-k** [comment]
Strange that this is not yet implemented, because i haven't seen or heard a better attentions technique so far. Please prove me wrong.

**Comment by Narsil** [comment]
Reason is simple, this implementation doesn't work exactly like sinks, the reason is KV cache handling because attention sinks require to slide everything except the sinks themselves, which makes AFAIK the KV cache invalid (since as soon as you slide once, the attention of the first non sink token is wrong, since it had been attending to non sinks before).
Prove me wrong.

@Bec-k No one is saying you're wrong. That doesn't mean we can implement the feature easily (or that it's worth the engineering time or maintenance cost) atm.

**Comment by xuan1905** [comment]
Attention Sinks caching has been [implemented in transformers](https://github.com/huggingface/transformers/commit/633215ba58fe5114d8c8d32e415a04600e010701). Really looking forward to the release of this feature on huggingface.

**Comment by Bec-k** [comment]
@OlivierDehaene attention cache have been added into the huggingface transformers package, it is implemented as a custom cache:
https://huggingface.co/docs/transformers/en/internal/generation_utils#transformers.SinkCache
https://github.com/huggingface/transformers/blob/main/src/transformers/cache_utils.py#L172
PR of integration into transformers library:
https://github.com/huggingface/transformers/pull/26681/files

Can you refactor "text-generation-inference" code to adapt this new feature? Does this solves initial problem?

**Comment by Bec-k** [comment]
Possibly you can forward that new Sinks Cache implementation in transformers and request additional changes for it to be properly implemented into your runtime?

**Pull request closed without merging**
