### PR TITLE
add support for CUDA 118 (suports H100s)

### PR DESCRIPTION
**Pull request by thelinuxkid**
# What does this PR do?

Adds support for torch  +cu188 (CUDA 118) which supports Nvidia H100s

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@OlivierDehaene OR @Narsil

### Torch version is updated
image

### Launcher runs
image

### Benchmarking runs

image

### Inference Runs on H100
image

### CODE REVIEW

**Comment by Narsil** [comment]
@thelinuxkid We're in the process of updating all our dependencies to 12.1 (to follow torch 2.1).

Thanks a lot for this PR, I hope it helps others.
We might take it to patch earlier versions, but going forward we'll use cuda 12.1.

Leaving it open for visibility for now.

**Comment by thelinuxkid** [comment]
Sounds good. Thanks @Narsil Let me know if there's anything I can help with.

**Comment by Rogerwyf** [comment]
@Narsil Can confirm separately that 1.2 is working on H100, with single GPU and multi-GPU deployment!

I do notice the performance of multi-GPU inference on H100 is actually pretty poor, but I will raise a separate issue for that.

**Comment by thelinuxkid** [comment]
HI guys, I haven't forgotten about this. Just haven't had a chance to upgrade our H100 to CUDA 12. As soon as I do I will report back.

**Comment by thelinuxkid** [comment]
Confirmed working on H100 and Cuda 12.1 
image
@Narsil

**Pull request closed without merging**
