### PR TITLE
Add support for other hardware accelerators

### PR DESCRIPTION
**Pull request by zhangsibo1129**
# What does this PR do?

Add support for other hardwares, such as Ascend NPU accelerator, while maintaining the original code logic and only adding a new hardware judgment branch.

```diff
         if torch.cuda.is_available():
             device = torch.device(f"cuda:{rank}")
             dtype = torch.float16 if dtype is None else dtype
+       elif is_torch_npu_available():
+           device = torch.device(f"npu:{rank}")
+           dtype = torch.float16 if dtype is None else dtype
         else:
             device = torch.device("cpu")
             dtype = torch.float32 if dtype is None else dtype
```
The initialization of the new hardware is placed in `server/text_generation_server/utils/import_utils.py` like `transformers` project.

```python
import importlib.util

def is_torch_npu_available(check_device=False):
    "Checks if `torch_npu` is installed and potentially if a NPU is in the environment"
    if importlib.util.find_spec("torch_npu") is None:
        return False

    import torch
    import torch_npu

    if check_device:
        try:
            # Will raise a RuntimeError if no NPU is found
            _ = torch.npu.device_count()
            return torch.npu.is_available()
        except RuntimeError:
            return False
    return hasattr(torch, "npu") and torch.npu.is_available()
```

[Ascend NPU](https://www.hiascend.com/en/) is an AI processor that support AI frameworks like PyTorch, TensorFlow, which has already integrated by [transformers](https://github.com/huggingface/transformers/pull/24879/commits/d4bb8f7995bc06144eaea727cb9d5056a17975d3), [accelerate](https://github.com/huggingface/accelerate/commit/c33adecc9f92808cbaeb0d34928e52e34180f964), [deepspeed](https://github.com/microsoft/DeepSpeed/commit/23a11a39510e2aefb48236e3d2672a7dcbfc42a3) and other popular LLM related software and tools.

## Use Cases

The models we have validated include Baichuan, Bloom, T5, Galactica, Llama2, OPT, Starcoder, Vicuna.  The actual supported models will be more, as the NPU has already been integrated into the `transformers`

The NPU hardware environment is as follows:
```shell
+------------------------------------------------------------------------------------------------+
| npu-smi 23.0.rc2                 Version: 23.0.rc2                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B1               | OK            | 89.2        46                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          26723/ 65536         |
+===========================+===============+====================================================+
| 1     910B1               | OK            | 93.3        50                0    / 0             |
| 0                         | 0000:01:00.0  | 0           0    / 0          4329 / 65536         |
+===========================+===============+====================================================+
| 2     910B1               | OK            | 87.0        48                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          4330 / 65536         |
+===========================+===============+====================================================+
| 3     910B1               | OK            | 100.9       49                0    / 0             |
| 0                         | 0000:02:00.0  | 0           0    / 0          4329 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| 0       0                 | 2902853       | text-generation          | 22420                   |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 3                                                            |
+===========================+===============+====================================================+
```

### Example of Baichuan2-7B-Chat

launching a model server
```shell
text-generation-launcher --model-id /data/models/Baichuan2-7B-Chat/ --max-input-length 128 --port 8081 --trust-remote-code
```
log info

```log
2023-10-10T01:24:12.945445Z  INFO text_generation_launcher: Args { model_id: "/data/models/Baichuan2-7B-Chat/", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 128, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "ascend-2", port: 8081, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-10-10T01:24:12.945499Z  WARN text_generation_launcher: `trust_remote_code` is set. Trusting that model `/data/models/Baichuan2-7B-Chat/` do not contain malicious code.
2023-10-10T01:24:12.945632Z  INFO download: text_generation_launcher: Starting download process.
2023-10-10T01:24:15.834308Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-10-10T01:24:16.352181Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-10-10T01:24:16.352443Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-10-10T01:24:19.411855Z  WARN text_generation_launcher: We're not using custom kernels.

2023-10-10T01:24:19.417047Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: No module named 'vllm_cache_ops'

2023-10-10T01:24:19.419766Z  WARN text_generation_launcher: Could not import Mistral model: No module named 'dropout_layer_norm'

2023-10-10T01:24:26.359116Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-10T01:28:36.507459Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-10T01:28:46.513610Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-10-10T01:28:47.324267Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-10-10T01:28:47.414188Z  INFO shard-manager: text_generation_launcher: Shard ready in 271.060993266s rank=0
2023-10-10T01:28:47.500971Z  INFO text_generation_launcher: Starting Webserver
2023-10-10T01:28:47.521717Z  WARN text_generation_router: router/src/main.rs:166: Could not find a fast tokenizer implementation for /data/models/Baichuan2-7B-Chat/
2023-10-10T01:28:47.521768Z  WARN text_generation_router: router/src/main.rs:169: Rust input length validation and truncation is disabled
2023-10-10T01:28:47.521774Z  WARN text_generation_router: router/src/main.rs:194: no pipeline tag found for model /data/models/Baichuan2-7B-Chat/
2023-10-10T01:28:47.582463Z  INFO text_generation_router: router/src/main.rs:213: Warming up model
2023-10-10T01:29:20.191046Z  WARN text_generation_router: router/src/main.rs:224: Model does not support automatic max batch total tokens
2023-10-10T01:29:20.191073Z  INFO text_generation_router: router/src/main.rs:246: Setting max batch total tokens to 16000
2023-10-10T01:29:20.191078Z  INFO text_generation_router: router/src/main.rs:247: Connected
2023-10-10T01:29:20.191085Z  WARN text_generation_router: router/src/main.rs:252: Invalid hostname, defaulting to 0.0.0.0
```

request
```shell
curl 127.0.0.1:8081/generate \
    -X POST \
    -d '{"inputs":"role: user, content: 解释一下“温故而知新”","parameters":{"max_new_tokens":50}}' \
    -H 'Content-Type: application/json'
```

response
```shell
{"generated_text":"这句话的含义\n\n\"温故而知新\"这句话出自《论语·为政》，是孔子的一句名言。它的意思是通过回顾和复习过去的知识，可以发现新的知识和道理。这句话强调了学习和成长的过程，即不断地回顾和总结过去的"}
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@Narsil

### CODE REVIEW

**Review by statelesshz — APPROVED** [review]

**Comment by zhangsibo1129** [comment]
@Narsil @OlivierDehaene Can you help review the code?

**Review by abhilash1910 — APPROVED** [review]
This looks like a good addition, IMO.  cc @muellerzr  could you help let us know if this addition seems ok? (since device abstraction is almost completed in huggingface stack). This would help me to add our logic as well.

**Comment by BrightXiaoHan** [comment]
> # What does this PR do?
> Add support for other hardwares, such as Ascend NPU accelerator, while maintaining the original code logic and only adding a new hardware judgment branch.
> 
> ```diff
>          if torch.cuda.is_available():
>              device = torch.device(f"cuda:{rank}")
>              dtype = torch.float16 if dtype is None else dtype
> +       elif is_torch_npu_available():
> +           device = torch.device(f"npu:{rank}")
> +           dtype = torch.float16 if dtype is None else dtype
>          else:
>              device = torch.device("cpu")
>              dtype = torch.float32 if dtype is None else dtype
> ```
> 
> The initialization of the new hardware is placed in `server/text_generation_server/utils/import_utils.py` like `transformers` project.
> 
> ```python
> import importlib.util
> 
> def is_torch_npu_available(check_device=False):
>     "Checks if `torch_npu` is installed and potentially if a NPU is in the environment"
>     if importlib.util.find_spec("torch_npu") is None:
>         return False
> 
>     import torch
>     import torch_npu
> 
>     if check_device:
>         try:
>             # Will raise a RuntimeError if no NPU is found
>             _ = torch.npu.device_count()
>             return torch.npu.is_available()
>         except RuntimeError:
>             return False
>     return hasattr(torch, "npu") and torch.npu.is_available()
> ```
> 
> [Ascend NPU](https://www.hiascend.com/en/) is an AI processor that support AI frameworks like PyTorch, TensorFlow, which has already integrated by [transformers](https://github.com/huggingface/transformers/pull/24879/commits/d4bb8f7995bc06144eaea727cb9d5056a17975d3), [accelerate](https://github.com/huggingface/accelerate/commit/c33adecc9f92808cbaeb0d34928e52e34180f964), [deepspeed](https://github.com/microsoft/DeepSpeed/commit/23a11a39510e2aefb48236e3d2672a7dcbfc42a3) and other popular LLM related software and tools.
> 
> ## Use Cases
> The models we have validated include Baichuan, Bloom, T5, Galactica, Llama2, OPT, Starcoder, Vicuna. The actual supported models will be more, as the NPU has already been integrated into the `transformers`
> 
> The NPU hardware environment is as follows:
> 
> ```shell
> +------------------------------------------------------------------------------------------------+
> | npu-smi 23.0.rc2                 Version: 23.0.rc2                                             |
> +---------------------------+---------------+----------------------------------------------------+
> | NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
> | Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
> +===========================+===============+====================================================+
> | 0     910B1               | OK            | 89.2        46                0    / 0             |
> | 0                         | 0000:C1:00.0  | 0           0    / 0          26723/ 65536         |
> +===========================+===============+====================================================+
> | 1     910B1               | OK            | 93.3        50                0    / 0             |
> | 0                         | 0000:01:00.0  | 0           0    / 0          4329 / 65536         |
> +===========================+===============+====================================================+
> | 2     910B1               | OK            | 87.0        48                0    / 0             |
> | 0                         | 0000:C2:00.0  | 0           0    / 0          4330 / 65536         |
> +===========================+===============+====================================================+
> | 3     910B1               | OK            | 100.9       49                0    / 0             |
> | 0                         | 0000:02:00.0  | 0           0    / 0          4329 / 65536         |
> +===========================+===============+====================================================+
> +---------------------------+---------------+----------------------------------------------------+
> | NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
> +===========================+===============+====================================================+
> | 0       0                 | 2902853       | text-generation          | 22420                   |
> +===========================+===============+====================================================+
> | No running processes found in NPU 1                                                            |
> +===========================+===============+====================================================+
> | No running processes found in NPU 2                                                            |
> +===========================+===============+====================================================+
> | No running processes found in NPU 3                                                            |
> +===========================+===============+====================================================+
> ```
> 
> ### Example of Baichuan2-7B-Chat
> launching a model server
> 
> ```shell
> text-generation-launcher --model-id /data/models/Baichuan2-7B-Chat/ --max-input-length 128 --port 8081 --trust-remote-code
> ```
> 
> log info
> 
> ```
> 2023-10-10T01:24:12.945445Z  INFO text_generation_launcher: Args { model_id: "/data/models/Baichuan2-7B-Chat/", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 128, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "ascend-2", port: 8081, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
> 2023-10-10T01:24:12.945499Z  WARN text_generation_launcher: `trust_remote_code` is set. Trusting that model `/data/models/Baichuan2-7B-Chat/` do not contain malicious code.
> 2023-10-10T01:24:12.945632Z  INFO download: text_generation_launcher: Starting download process.
> 2023-10-10T01:24:15.834308Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.
> 
> 2023-10-10T01:24:16.352181Z  INFO download: text_generation_launcher: Successfully downloaded weights.
> 2023-10-10T01:24:16.352443Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
> 2023-10-10T01:24:19.411855Z  WARN text_generation_launcher: We're not using custom kernels.
> 
> 2023-10-10T01:24:19.417047Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: No module named 'vllm_cache_ops'
> 
> 2023-10-10T01:24:19.419766Z  WARN text_generation_launcher: Could not import Mistral model: No module named 'dropout_layer_norm'
> 
> 2023-10-10T01:24:26.359116Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
> 2023-10-10T01:28:36.507459Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
> 2023-10-10T01:28:46.513610Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
> 2023-10-10T01:28:47.324267Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0
> 
> 2023-10-10T01:28:47.414188Z  INFO shard-manager: text_generation_launcher: Shard ready in 271.060993266s rank=0
> 2023-10-10T01:28:47.500971Z  INFO text_generation_launcher: Starting Webserver
> 2023-10-10T01:28:47.521717Z  WARN text_generation_router: router/src/main.rs:166: Could not find a fast tokenizer implementation for /data/models/Baichuan2-7B-Chat/
> 2023-10-10T01:28:47.521768Z  WARN text_generation_router: router/src/main.rs:169: Rust input length validation and truncation is disabled
> 2023-10-10T01:28:47.521774Z  WARN text_generation_router: router/src/main.rs:194: no pipeline tag found for model /data/models/Baichuan2-7B-Chat/
> 2023-10-10T01:28:47.582463Z  INFO text_generation_router: router/src/main.rs:213: Warming up model
> 2023-10-10T01:29:20.191046Z  WARN text_generation_router: router/src/main.rs:224: Model does not support automatic max batch total tokens
> 2023-10-10T01:29:20.191073Z  INFO text_generation_router: router/src/main.rs:246: Setting max batch total tokens to 16000
> 2023-10-10T01:29:20.191078Z  INFO text_generation_router: router/src/main.rs:247: Connected
> 2023-10-10T01:29:20.191085Z  WARN text_generation_router: router/src/main.rs:252: Invalid hostname, defaulting to 0.0.0.0
> ```
> 
> request
> 
> ```shell
> curl 127.0.0.1:8081/generate \
>     -X POST \
>     -d '{"inputs":"role: user, content: 解释一下“温故而知新”","parameters":{"max_new_tokens":50}}' \
>     -H 'Content-Type: application/json'
> ```
> 
> response
> 
> ```shell
> {"generated_text":"这句话的含义\n\n\"温故而知新\"这句话出自《论语·为政》，是孔子的一句名言。它的意思是通过回顾和复习过去的知识，可以发现新的知识和道理。这句话强调了学习和成长的过程，即不断地回顾和总结过去的"}
> ```
> 
> ## Before submitting
> * [ ]  This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
> * [x]  Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
>   Pull Request section?
> * [ ]  Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
>   to it if that's the case.
> * [x]  Did you make sure to update the documentation with your changes? Here are the
>   [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
>   [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
> * [ ]  Did you write any new necessary tests?
> 
> ## Who can review?
> @Narsil

Hi. How much throughput acceleration can be provided on the Ascend 910B?

**Comment by BrightXiaoHan** [comment]
Is it possible to start on all npu devices?

**Comment by statelesshz** [comment]
> Is it possible to start on all npu devices?

Hi @BrightXiaoHan, this PR is only tested on 910B.

**Comment by Narsil** [comment]
Currently we're not going to include this code.

We do support alternate backends, however we try to make it as fast as possible, usually meaning a dedicated backend like https://github.com/huggingface/optimum-neuron/tree/main/text-generation-inference
Or support in this repo when the modified code is minimal (like AMD).

**Pull request closed without merging**
