### PR TITLE
fp8 marlin kernel

### PR DESCRIPTION
**Pull request by flozi00**
Adopted from: https://github.com/vllm-project/vllm/commit/47f0954af0a5aefd0db19875f6bdcbe933d055a9

Pinging @danieldk for interest since he added the marlin kernels

### CODE REVIEW

**Comment by danieldk** [comment]
So this would enable FP8 support pre-H100 when using `quantize="fp8"` when wired up?

**Comment by flozi00** [comment]
Yes, exactly

**Comment by flozi00** [comment]
@danieldk could you please take a look for the packing ?
I am not sure how to repack the normal weights into marlin format with your functions.

Please feel free to overtake this PR if it's a fast shot :)

**Comment by danieldk** [comment]
> @danieldk could you please take a look for the packing ? I am not sure how to repack the normal weights into marlin format with your functions.

I was hoping/thinking that this could just hook into

https://github.com/huggingface/text-generation-inference/blob/5c7c9f13903f09636aaf99210710bf07002cdb87/server/text_generation_server/layers/fp8.py#L21

for compute capabilities that don't support FP8 directly, but that are supported by this Marlin kernel? I don't think it needs any special packing?

**Comment by danieldk** [comment]
Ok, so I think we need to:

1. Convert to int32, though we may want to check what torch's representation is and whether it's possible to cast instead.
2. Run `gptq_marlin_repack` (with empty `perm`/`g_idx`).
3. Permute `scales` (see gptq repack).
4. The result the repack can be used as `B` in the marlin FP8 gemm.

**Comment by flozi00** [comment]
Just pushed changes, do you mean that style ? @danieldk

**Comment by danieldk** [comment]
> Just pushed changes, do you mean that style ? @danieldk

Yeah, that looks in the direction that I was thinking. The scales need to be repeated in the output features dimension before permuting.

Let me know if you want to continue working on this or whether I should pick it up. I can probably do it this week between other things.

**Comment by flozi00** [comment]
It would be great if you could take this, since I got some emergencies over night it have to prioritize, so it would be faster if you would finish it I think.

**Comment by danieldk** [comment]
> It would be great if you could take this, since I got some emergencies over night it have to prioritize, so it would be faster if you would finish it I think.

Ok, I'll work on it. Best of luck with the emergencies!

**Comment by danieldk** [comment]
Closing this in favor of #2213 (to run CI).

**Pull request closed without merging**
