### PR TITLE
WIP add exllamav2

### PR DESCRIPTION
**Pull request by flozi00**
# What does this PR do?

Fixes # (issue) https://github.com/huggingface/text-generation-inference/issues/1016

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by flozi00** [comment]
could you start the workflows for testing ?
Just replaced the exllama1 layer by exllama 2

To be honest i just did coding without running right now, taking some free time to work on this when its possible.

Would not worry if someone wants to take this PR and finish it

**Comment by Narsil** [comment]
Hey I was off for a few weeks therefore couldn't look.

Where did you inspire your code from, cannot find any reference in the exllamav2 implementation  https://github.com/turboderp/exllamav2/tree/master here.

**Comment by Narsil** [comment]
I managed to make it build an run but go some illegal access error: https://github.com/huggingface/text-generation-inference/pull/1211

**Comment by SunMarc** [comment]
Hey @Narsil, it's probably because it is missing this [piece](https://github.com/PanQiWei/AutoGPTQ/blob/298d907c5c9406ce9f8e0a4acc0b1518b4cfcc81/auto_gptq/modeling/_utils.py#L352C9-L352C9) where we create the buffers and build the q4 matrix for each linear.

**Comment by Narsil** [comment]
Still failing with the scratch space (dummy output)

**Comment by flozi00** [comment]
> Hey I was off for a few weeks therefore couldn't look.
> 
> Where did you inspire your code from, cannot find any reference in the exllamav2 implementation https://github.com/turboderp/exllamav2/tree/master here.


Hi, thanks for taking this.
Reference implementations are from autogptq and optimum pull requests.

**Comment by Narsil** [comment]
Oh but wait, exllamav2 models are different from regular GPTQ models, right ?

`q_weight` vs `qweight`.

I'm wondering if I just didn't test on an appropriate model (and we should change the loading part to distinguish between gptq and exllamav2).

https://github.com/PanQiWei/AutoGPTQ/blob/main/auto_gptq/nn_modules/qlinear/qlinear_exllamav2.py#L38

@SunMarc since you have done the integration in AutoGPTQ.

**Comment by SunMarc** [comment]
Hi @Narsil, Exllamav2 kernel are also compatible with GPTQ model. I've tested with popular model like [LLama2-7B-GPTQ](https://huggingface.co/TheBloke/Llama-2-7B-GPTQ) and it should work. I didn't add the support with EXL2 format as it is still being tested and the performance is about the same.

**Comment by Narsil** [comment]
Shoot, this is the one I was trying out, it's definitely outputting garbage (quite fast, but still garbage)

**Comment by flozi00** [comment]
Do you have some numbers about how fast it is compared to v1 ?
If i can help in any way please tell me, but next two weeks wont be much time available

**Comment by fxmarty** [comment]
maybe related https://github.com/PanQiWei/AutoGPTQ/issues/412

**Pull request closed without merging**
