### PR TITLE
Fixing top_k tokens when k ends up < 0

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Narsil** [comment]
@Vinno97

**Comment by Narsil** [comment]
This seems to be triggerable on some GPTQ models (it was for me on a very bad checkpoint).

**Comment by Vinno97** [comment]
Hi @Narsil do you have a way to reproduce this? Might be good to also add it to the tests.
How I'm reading the logic:

* This fixes `top_n_ishes` being empty for a certain batch item (request).
* Which should only happen when no logprob is higher or equal to the `nth_highest` logprob.
* Which may happen when all logprobs for thatrequest are are `-inf`?

**Comment by Narsil** [comment]
Yes that's basically it. It was a trash model outputting garbage, therefore we could hit this.

However the fix shouldn't have any impact except let the queries go and not crash.

**Comment by Vinno97** [comment]
Okay fair enough. Was thinking of catching this earlier in the process, but this works and is good enough

**Pull request merged**
