### PR TITLE
This should prevent the PyTorch overriding.

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Narsil** [comment]
Fixed #739

**Comment by chiragjn** [comment]
Looking at this commit: https://github.com/huggingface/text-generation-inference/commit/bce5e22444aab16a3e3cc0a9b7caeab5ad33b16e

This removes the `+cu118` suffix and version 2.0.1 on pypi uses cuda 11.7
Wouldn't that reintroduce this problem?

**Comment by Narsil** [comment]
Lots of other parts of the build are complaining about non standard versionning with +cu118...

Poetry for one keeps looping in search for a version.

**Comment by Narsil** [comment]
Currently the problem is not reintroduced afaik because we're preinstalling 2.0.1 with cu118 and no one is overriding it in subsequent dependencies. 

It is however likely to occur again should there be more minors in torch and dependencies upgrading somehow.

**Pull request merged**
