### PR TITLE
Directly load GPTBigCode to specified device

### PR DESCRIPTION
**Pull request by Atry**
This PR directly load GPTBigCode to specified device, avoiding moving model between devices.

# What does this PR do?
This PR directly load GPTBigCode to specified device, avoiding moving model between devices.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@OlivierDehaene OR @Narsil

### CODE REVIEW

**Review by Narsil — APPROVED** [review]
LGTM.

**Comment by Atry** [comment]
Reopen this PR to trigger a CI run

**Comment by Narsil** [comment]
It won' work, you just don't have access to our secrets so the CI will not work.

**Comment by Atry** [comment]
I wonder if you would like to set a `pull_request_target` event in GitHub Actions so that CI can be run for contributors

See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

**Pull request merged**
