### PR TITLE
Feature: During Generation add support for no_repeat_ngram_size

### LINKED ISSUE #2219: Support for no_repeat_ngram_size generation parameter
### Feature request

The Transformers library supports the no_repeat_ngram_size parameter for generation. https://huggingface.co/docs/transformers/v4.18.0/en/main_classes/text_generation#transformers.generation_utils.GenerationMixin.generate.no_repeat_ngram_size 
Could this be supported in the TGI library?

### Motivation

This parameter helps to cut down on repetition and helps generate more concise responses.

### Your contribution

I would be happy to help implement this if I can get some pointers about what code needs to be adjusted to accommodate the change? It's unclear to me whether the change needs to be implemented in the Rust layer, the Python layer, or both.

I'd like the parameter to be supported for Llama type models (Llama, Mistral, Phi, etc).

Thanks!

### PR DESCRIPTION
**Pull request by njbrake**
# What does this PR do?

Fixes #2219 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@ErikKaum

### CODE REVIEW

**Comment by ErikKaum** [comment]
Awesome, thanks for the PR @njbrake 💯 

Is it ready for review? I could take a closer look at the end of the week 👍 I'll also need to make a branch from my user to run the CI (more as an fyi)

**Comment by njbrake** [comment]
> Awesome, thanks for the PR @njbrake 💯
> 
> Is it ready for review? I could take a closer look at the end of the week 👍 I'll also need to make a branch from my user to run the CI (more as an fyi)

Hi, yes ready for review! 🚀

**Comment by njbrake** [comment]
Hi @ErikKaum thanks for the check. Due to some firewall issues I can't actually build the server locally: I can pull a built docker image but that's about it, so I'm slightly "running blind" with respect to these changes. From your error stack (thanks for providing that 💯 ) I realized that I had added the no_repeat_ngram logic as a warper, but it's actually a processor, so it needed to go into a slghtly different place. I've refactored the code appropriately and believe that it should now work as expected. Would you be able to give it a try?

**Comment by ErikKaum** [comment]
Thank you @njbrake 🙌 

There was I think one place where the `NoRepeatNgramLogitsProcessor` was still used so I deleted it and after that everything compiled and I was able to use it in inference. Let me still verify that all test run and make sure there aren't logical errors in the logit processing.

I've had to make a separate PR so I can run the CI: https://github.com/huggingface/text-generation-inference/pull/2308

**Comment by njbrake** [comment]
@ErikKaum Ooh thank you for catching that! Let me know what else I can do to help out.

**Pull request closed without merging**
