### PR TITLE
BNB 4Bit, 0.40.0 release

### PR DESCRIPTION
**Pull request by flozi00**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Narsil** [comment]
I modified it to make it work and I'm seeing 2x *increased* latency....

Regular falcon-7b (A10G, not sharded)
```
| Step           | Batch Size | Average   | Lowest    | Highest   | p50       | p90       | p99       |
|----------------|------------|-----------|-----------|-----------|-----------|-----------|-----------|
| Prefill        | 1          | 33.84 ms  | 33.73 ms  | 34.22 ms  | 33.82 ms  | 34.22 ms  | 34.22 ms  |
|                | 2          | 35.57 ms  | 35.44 ms  | 35.75 ms  | 35.60 ms  | 35.75 ms  | 35.75 ms  |
|                | 4          | 37.18 ms  | 37.10 ms  | 37.28 ms  | 37.18 ms  | 37.28 ms  | 37.28 ms  |
|                | 8          | 41.02 ms  | 40.88 ms  | 41.16 ms  | 41.03 ms  | 41.16 ms  | 41.16 ms  |
|                | 16         | 59.12 ms  | 59.03 ms  | 59.21 ms  | 59.13 ms  | 59.21 ms  | 59.21 ms  |
|                | 32         | 95.52 ms  | 95.20 ms  | 96.10 ms  | 95.50 ms  | 96.10 ms  | 96.10 ms  |
| Decode (token) | 1          | 31.81 ms  | 31.75 ms  | 31.89 ms  | 31.79 ms  | 31.87 ms  | 31.87 ms  |
|                | 2          | 33.02 ms  | 32.96 ms  | 33.23 ms  | 33.00 ms  | 32.98 ms  | 32.98 ms  |
|                | 4          | 33.12 ms  | 33.09 ms  | 33.17 ms  | 33.13 ms  | 33.10 ms  | 33.10 ms  |
|                | 8          | 33.43 ms  | 33.40 ms  | 33.47 ms  | 33.44 ms  | 33.42 ms  | 33.42 ms  |
|                | 16         | 34.05 ms  | 34.02 ms  | 34.08 ms  | 34.05 ms  | 34.05 ms  | 34.05 ms  |
|                | 32         | 35.73 ms  | 35.66 ms  | 35.86 ms  | 35.72 ms  | 35.86 ms  | 35.86 ms  |
| Decode (total) | 1          | 222.68 ms | 222.23 ms | 223.23 ms | 222.53 ms | 223.09 ms | 223.09 ms |
|                | 2          | 231.11 ms | 230.74 ms | 232.61 ms | 231.03 ms | 230.88 ms | 230.88 ms |
|                | 4          | 231.86 ms | 231.62 ms | 232.18 ms | 231.94 ms | 231.74 ms | 231.74 ms |
|                | 8          | 234.04 ms | 233.81 ms | 234.27 ms | 234.09 ms | 233.94 ms | 233.94 ms |
|                | 16         | 238.34 ms | 238.16 ms | 238.56 ms | 238.39 ms | 238.33 ms | 238.33 ms |
|                | 32         | 250.10 ms | 249.59 ms | 251.00 ms | 250.06 ms | 251.00 ms | 251.00 ms |


| Step    | Batch Size | Average            | Lowest             | Highest            |
|---------|------------|--------------------|--------------------|--------------------|
| Prefill | 1          | 29.55 tokens/secs  | 29.22 tokens/secs  | 29.65 tokens/secs  |
|         | 2          | 56.23 tokens/secs  | 55.95 tokens/secs  | 56.44 tokens/secs  |
|         | 4          | 107.59 tokens/secs | 107.28 tokens/secs | 107.82 tokens/secs |
|         | 8          | 195.03 tokens/secs | 194.34 tokens/secs | 195.72 tokens/secs |
|         | 16         | 270.64 tokens/secs | 270.23 tokens/secs | 271.03 tokens/secs |
|         | 32         | 335.01 tokens/secs | 332.99 tokens/secs | 336.11 tokens/secs |
| Decode  | 1          | 31.44 tokens/secs  | 31.36 tokens/secs  | 31.50 tokens/secs  |
|         | 2          | 60.58 tokens/secs  | 60.19 tokens/secs  | 60.67 tokens/secs  |
|         | 4          | 120.76 tokens/secs | 120.60 tokens/secs | 120.89 tokens/secs |
|         | 8          | 239.28 tokens/secs | 239.04 tokens/secs | 239.51 tokens/secs |
|         | 16         | 469.93 tokens/secs | 469.49 tokens/secs | 470.26 tokens/secs |
|         | 32         | 895.63 tokens/secs | 892.41 tokens/secs | 897.47 tokens/secs |
```

BNB 4bits (FP4+NF4) on the same model + hardware:

```
| Step           | Batch Size | Average   | Lowest    | Highest   | p50       | p90       | p99       |
|----------------|------------|-----------|-----------|-----------|-----------|-----------|-----------|
| Prefill        | 1          | 71.66 ms  | 71.61 ms  | 71.73 ms  | 71.67 ms  | 71.73 ms  | 71.73 ms  |
|                | 2          | 76.35 ms  | 76.03 ms  | 77.16 ms  | 76.31 ms  | 77.16 ms  | 77.16 ms  |
|                | 4          | 77.29 ms  | 77.15 ms  | 77.36 ms  | 77.30 ms  | 77.36 ms  | 77.36 ms  |
|                | 8          | 81.29 ms  | 81.14 ms  | 81.40 ms  | 81.31 ms  | 81.40 ms  | 81.40 ms  |
|                | 16         | 99.38 ms  | 99.01 ms  | 100.22 ms | 99.28 ms  | 100.22 ms | 100.22 ms |
|                | 32         | 135.67 ms | 135.40 ms | 135.91 ms | 135.75 ms | 135.91 ms | 135.91 ms |
| Decode (token) | 1          | 25.47 ms  | 25.29 ms  | 26.61 ms  | 25.35 ms  | 26.61 ms  | 26.61 ms  |
|                | 2          | 73.59 ms  | 73.50 ms  | 73.65 ms  | 73.61 ms  | 73.59 ms  | 73.59 ms  |
|                | 4          | 73.73 ms  | 73.68 ms  | 73.79 ms  | 73.74 ms  | 73.72 ms  | 73.72 ms  |
|                | 8          | 74.03 ms  | 74.00 ms  | 74.08 ms  | 74.02 ms  | 74.01 ms  | 74.01 ms  |
|                | 16         | 74.44 ms  | 74.35 ms  | 74.50 ms  | 74.45 ms  | 74.47 ms  | 74.47 ms  |
|                | 32         | 75.97 ms  | 75.88 ms  | 76.16 ms  | 75.98 ms  | 76.16 ms  | 76.16 ms  |
| Decode (total) | 1          | 178.30 ms | 177.06 ms | 186.27 ms | 177.44 ms | 186.27 ms | 186.27 ms |
|                | 2          | 515.14 ms | 514.52 ms | 515.58 ms | 515.26 ms | 515.15 ms | 515.15 ms |
|                | 4          | 516.12 ms | 515.75 ms | 516.53 ms | 516.21 ms | 516.04 ms | 516.04 ms |
|                | 8          | 518.18 ms | 518.00 ms | 518.57 ms | 518.14 ms | 518.06 ms | 518.06 ms |
|                | 16         | 521.07 ms | 520.48 ms | 521.51 ms | 521.14 ms | 521.32 ms | 521.32 ms |
|                | 32         | 531.77 ms | 531.19 ms | 533.14 ms | 531.85 ms | 533.14 ms | 533.14 ms |


| Step    | Batch Size | Average            | Lowest             | Highest            |
|---------|------------|--------------------|--------------------|--------------------|
| Prefill | 1          | 13.95 tokens/secs  | 13.94 tokens/secs  | 13.96 tokens/secs  |
|         | 2          | 26.19 tokens/secs  | 25.92 tokens/secs  | 26.31 tokens/secs  |
|         | 4          | 51.75 tokens/secs  | 51.70 tokens/secs  | 51.84 tokens/secs  |
|         | 8          | 98.41 tokens/secs  | 98.28 tokens/secs  | 98.60 tokens/secs  |
|         | 16         | 161.00 tokens/secs | 159.65 tokens/secs | 161.60 tokens/secs |
|         | 32         | 235.86 tokens/secs | 235.44 tokens/secs | 236.33 tokens/secs |
| Decode  | 1          | 39.27 tokens/secs  | 37.58 tokens/secs  | 39.54 tokens/secs  |
|         | 2          | 27.18 tokens/secs  | 27.15 tokens/secs  | 27.21 tokens/secs  |
|         | 4          | 54.25 tokens/secs  | 54.21 tokens/secs  | 54.29 tokens/secs  |
|         | 8          | 108.07 tokens/secs | 107.99 tokens/secs | 108.11 tokens/secs |
|         | 16         | 214.94 tokens/secs | 214.76 tokens/secs | 215.18 tokens/secs |
|         | 32         | 421.24 tokens/secs | 420.15 tokens/secs | 421.70 tokens/secs |
```

(I can provide the fixed version if you want).

Do you have similar benches ?

**Comment by Narsil** [comment]
Same story on Falcon-40b (shards =4 on 4 A10G)

```
| Step           | Batch Size | Average   | Lowest    | Highest    | p50       | p90        | p99        |
|----------------|------------|-----------|-----------|------------|-----------|------------|------------|
| Prefill        | 1          | 63.32 ms  | 63.00 ms  | 64.91 ms   | 63.14 ms  | 64.91 ms   | 64.91 ms   |
|                | 2          | 119.56 ms | 64.33 ms  | 397.30 ms  | 64.61 ms  | 397.30 ms  | 397.30 ms  |
|                | 4          | 136.67 ms | 71.54 ms  | 574.37 ms  | 71.95 ms  | 574.37 ms  | 574.37 ms  |
|                | 8          | 189.54 ms | 89.34 ms  | 886.00 ms  | 103.58 ms | 886.00 ms  | 886.00 ms  |
|                | 16         | 140.03 ms | 137.81 ms | 145.75 ms  | 139.19 ms | 145.75 ms  | 145.75 ms  |
|                | 32         | NaN ms    | NaN ms    | NaN ms     | NaN ms    | NaN ms     | NaN ms     |
| Decode (token) | 1          | 50.87 ms  | 50.64 ms  | 51.37 ms   | 50.85 ms  | 50.72 ms   | 50.72 ms   |
|                | 2          | 56.39 ms  | 56.21 ms  | 56.98 ms   | 56.38 ms  | 56.27 ms   | 56.27 ms   |
|                | 4          | 68.25 ms  | 58.09 ms  | 133.33 ms  | 58.41 ms  | 58.62 ms   | 58.62 ms   |
|                | 8          | 74.56 ms  | 61.64 ms  | 133.43 ms  | 72.52 ms  | 72.75 ms   | 72.75 ms   |
|                | 16         | 130.11 ms | 81.70 ms  | 204.56 ms  | 82.92 ms  | 203.72 ms  | 203.72 ms  |
|                | 32         | NaN ms    | NaN ms    | NaN ms     | NaN ms    | NaN ms     | NaN ms     |
| Decode (total) | 1          | 356.08 ms | 354.50 ms | 359.56 ms  | 355.96 ms | 355.03 ms  | 355.03 ms  |
|                | 2          | 394.76 ms | 393.50 ms | 398.90 ms  | 394.69 ms | 393.89 ms  | 393.89 ms  |
|                | 4          | 477.77 ms | 406.65 ms | 933.31 ms  | 408.91 ms | 410.38 ms  | 410.38 ms  |
|                | 8          | 521.95 ms | 431.45 ms | 934.02 ms  | 507.66 ms | 509.29 ms  | 509.29 ms  |
|                | 16         | 910.74 ms | 571.91 ms | 1431.92 ms | 580.41 ms | 1426.07 ms | 1426.07 ms |
|                | 32         | NaN ms    | NaN ms    | NaN ms     | NaN ms    | NaN ms     | NaN ms     |


| Step    | Batch Size | Average            | Lowest             | Highest            |
|---------|------------|--------------------|--------------------|--------------------|
| Prefill | 1          | 15.79 tokens/secs  | 15.41 tokens/secs  | 15.87 tokens/secs  |
|         | 2          | 25.99 tokens/secs  | 5.03 tokens/secs   | 31.09 tokens/secs  |
|         | 4          | 47.09 tokens/secs  | 6.96 tokens/secs   | 55.91 tokens/secs  |
|         | 8          | 71.52 tokens/secs  | 9.03 tokens/secs   | 89.55 tokens/secs  |
|         | 16         | 114.30 tokens/secs | 109.78 tokens/secs | 116.10 tokens/secs |
|         | 32         | NaN tokens/secs    | NaN tokens/secs    | NaN tokens/secs    |
| Decode  | 1          | 19.66 tokens/secs  | 19.47 tokens/secs  | 19.75 tokens/secs  |
|         | 2          | 35.47 tokens/secs  | 35.10 tokens/secs  | 35.58 tokens/secs  |
|         | 4          | 62.72 tokens/secs  | 30.00 tokens/secs  | 68.85 tokens/secs  |
|         | 8          | 113.05 tokens/secs | 59.96 tokens/secs  | 129.79 tokens/secs |
|         | 16         | 148.16 tokens/secs | 78.22 tokens/secs  | 195.84 tokens/secs |
|         | 32         | NaN tokens/secs    | NaN tokens/secs    | NaN tokens/secs    |
```

Vs (BNB4)

```
| Step           | Batch Size | Average    | Lowest    | Highest    | p50        | p90        | p99        |
|----------------|------------|------------|-----------|------------|------------|------------|------------|
| Prefill        | 1          | 197.22 ms  | 122.34 ms | 637.70 ms  | 122.93 ms  | 637.70 ms  | 637.70 ms  |
|                | 2          | 179.28 ms  | 124.76 ms | 660.35 ms  | 126.14 ms  | 660.35 ms  | 660.35 ms  |
|                | 4          | 288.57 ms  | 132.29 ms | 659.63 ms  | 133.61 ms  | 659.63 ms  | 659.63 ms  |
|                | 8          | 334.31 ms  | 149.55 ms | 636.72 ms  | 150.09 ms  | 636.72 ms  | 636.72 ms  |
|                | 16         | 208.12 ms  | 197.41 ms | 299.67 ms  | 198.05 ms  | 299.67 ms  | 299.67 ms  |
|                | 32         | NaN ms     | NaN ms    | NaN ms     | NaN ms     | NaN ms     | NaN ms     |
| Decode (token) | 1          | 61.82 ms   | 58.04 ms  | 64.86 ms   | 62.80 ms   | 63.05 ms   | 63.05 ms   |
|                | 2          | 130.60 ms  | 116.68 ms | 196.98 ms  | 117.81 ms  | 116.78 ms  | 116.78 ms  |
|                | 4          | 119.03 ms  | 118.83 ms | 119.28 ms  | 119.13 ms  | 118.94 ms  | 118.94 ms  |
|                | 8          | 122.60 ms  | 122.19 ms | 123.00 ms  | 122.70 ms  | 122.66 ms  | 122.66 ms  |
|                | 16         | 170.25 ms  | 126.63 ms | 229.68 ms  | 202.35 ms  | 203.56 ms  | 203.56 ms  |
|                | 32         | NaN ms     | NaN ms    | NaN ms     | NaN ms     | NaN ms     | NaN ms     |
| Decode (total) | 1          | 432.71 ms  | 406.28 ms | 454.01 ms  | 439.63 ms  | 441.37 ms  | 441.37 ms  |
|                | 2          | 914.17 ms  | 816.78 ms | 1378.87 ms | 824.64 ms  | 817.46 ms  | 817.46 ms  |
|                | 4          | 833.22 ms  | 831.84 ms | 834.92 ms  | 833.89 ms  | 832.57 ms  | 832.57 ms  |
|                | 8          | 858.23 ms  | 855.31 ms | 861.01 ms  | 858.87 ms  | 858.61 ms  | 858.61 ms  |
|                | 16         | 1191.72 ms | 886.39 ms | 1607.76 ms | 1416.45 ms | 1424.89 ms | 1424.89 ms |
|                | 32         | NaN ms     | NaN ms    | NaN ms     | NaN ms     | NaN ms     | NaN ms     |


| Step    | Batch Size | Average            | Lowest            | Highest            |
|---------|------------|--------------------|-------------------|--------------------|
| Prefill | 1          | 6.95 tokens/secs   | 1.57 tokens/secs  | 8.17 tokens/secs   |
|         | 2          | 14.61 tokens/secs  | 3.03 tokens/secs  | 16.03 tokens/secs  |
|         | 4          | 22.92 tokens/secs  | 6.06 tokens/secs  | 30.24 tokens/secs  |
|         | 8          | 37.27 tokens/secs  | 12.56 tokens/secs | 53.49 tokens/secs  |
|         | 16         | 78.08 tokens/secs  | 53.39 tokens/secs | 81.05 tokens/secs  |
|         | 32         | NaN tokens/secs    | NaN tokens/secs   | NaN tokens/secs    |
| Decode  | 1          | 16.20 tokens/secs  | 15.42 tokens/secs | 17.23 tokens/secs  |
|         | 2          | 15.75 tokens/secs  | 10.15 tokens/secs | 17.14 tokens/secs  |
|         | 4          | 33.60 tokens/secs  | 33.54 tokens/secs | 33.66 tokens/secs  |
|         | 8          | 65.25 tokens/secs  | 65.04 tokens/secs | 65.47 tokens/secs  |
|         | 16         | 100.58 tokens/secs | 69.66 tokens/secs | 126.36 tokens/secs |
|         | 32         | NaN tokens/secs    | NaN tokens/secs   | NaN tokens/secs    |
```

**Comment by flozi00** [comment]
Yeah, I had no time to test it right now
Could you share the fixed version ?
I will run tests and benchs later this week

**Comment by flozi00** [comment]
Falcon in it's quantized version always goes slower as far I know
Maybe llama will run better
Falcon + gptq is slower than fp16 too (not tried tgi gptq, only autogptq)

**Comment by Narsil** [comment]
https://github.com/huggingface/text-generation-inference/tree/bnb4

**Comment by Narsil** [comment]
I tried falcon because it's easier to share and compare results than any llama derived models because everyone have their own versions..

**Pull request closed without merging**
