### PR TITLE
Print error logs from launcher during integration tests

### PR DESCRIPTION
**Pull request by Atry**
# What does this PR do?
Print error logs from launcher during integration tests

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@OlivierDehaene OR @Narsil

### CODE REVIEW

**Comment by Narsil** [comment]
Hey @Atry thanks for the contribution.

Do you mind sharing a bit more about the problem this is trying to solve ?

**Comment by Atry** [comment]
I should be able to see error logs when running a test. The error logs are useful to debug failed tests.

**Comment by OlivierDehaene** [comment]
But that's already the case with the `-s` pytest arg isn't it?

**Comment by Atry** [comment]
The `-s` option affects how to capture `pytest`'s stdout and stderr, but it does not affect the `launcher`'s stderr in the current implementation, because `launcher`'s stderr is not forwarded to `pytest`.

This PR redirect the `launcher`'s stderr to the `launcher`'s stdout, which is already forwarded to `pytest`'s stderr at https://github.com/huggingface/text-generation-inference/pull/480/files#diff-f99db5aabf9de5120c24409d7be1b79e635a807f5dc3c12de0116b66f5528be2R256, solving this problem.

**Comment by Atry** [comment]
Hi @OlivierDehaene, could you trigger the CI for this PR? You will see more logs than the `main` branch.

**Pull request closed without merging**
